### ISSUE TITLE
error in install reverb

### ISSUE THREAD

**Issue by thunanguyen** [deepmind/acme#1]
Hi, when I install reverb in Window. It spills out an error like this:

ERROR: Could not find a version that satisfies the requirement dm-reverb-nightly==0.1.0.dev20200529; extra == "reverb" (from dm-acme[reverb]) (from versions: none)

ERROR: No matching distribution found for dm-reverb-nightly==0.1.0.dev20200529; extra == "reverb" (from dm-acme[reverb])

**Comment by fastturtle** [comment]
Thanks for the interest! At the moment Reverb does not support Windows, and likely will not for the forseeable future. If you don’t have access to a Linux OS you can always use docker to try out Acme!
