### ISSUE TITLE
MPO implementation

### ISSUE THREAD

**Issue by yesiam-png** [deepmind/acme#104]
Hi, when I check the MPO code, I have a problem with the optimization of the Lagrange multiplier eta in Eq. (9) in the MPO paper (https://arxiv.org/pdf/1806.06920.pdf), which corresponds to the `loss_temperature`, i.e, https://github.com/deepmind/acme/blob/636263fa34826b22231c2b5ef8bdc59cf92defed/acme/tf/losses/mpo.py#L351. In my opinion, I think `online_action_distribution ` should also be multiplied as per Eq. (9) in the MPO paper.

**Comment by bshahr** [comment]
Hi yesiam-png,

Thanks for your questions! If you look at Eq (9) from the paper, you'll notice that we've replaced the integral with respect to pi with a Monte Carlo estimate, using actions sampled from pi. When you do this, you notice that that integral turns into the logsumexp you see in that line of code along with a `-log_num_actions` corresponding to the `log(1/num_action_samples)` that would come from averaging over the samples.

Best,

Bobak
