### ISSUE TITLE
What is the correct way to change the observation dtype?

### ISSUE THREAD

**Issue by jmribeiro** [deepmind/acme#107]
Hi!

I'm setting up an MLP DQN for CartPole and the snt MLP requires the datatype to be float32.
Do I need to wrap the env, converting the observations from float64 to float32 before passing env to GymWrapper or is there a simpler way (argument somewhere, etc...)

Thanks

**Comment by alaterre** [comment]
You can use the provided [single-precision wrapper](https://github.com/deepmind/acme/blob/dbdbe5f12c740242b8504b9426e52a239dace071/acme/wrappers/single_precision.py#L27). For a gym env for instance, it gives:

```python
def create_gym_environment(game_name: str, evaluation: bool = False) -> dm_env.Environment:
    """Wraps an Gym environment with some basic preprocessing.

    Args:
        game_name: str, the name of the gym environment.
        evaluation: bool, to change the behaviour during evaluation.

    Returns:
        A Gym environment with some standard preprocessing.
    """
    del evaluation

    game_version = "v0"
    full_game_name = "{}-{}".format(game_name, game_version)
    env = gym.make(full_game_name)

    return wrappers.wrap_all(
        env, [wrappers.gym_wrapper.GymWrapper, wrappers.SinglePrecisionWrapper]
    )
```

**Comment by jmribeiro** [comment]
Thanks!
