### ISSUE TITLE
Issues when running r2d2 agent 

### ISSUE THREAD

**Issue by apoorvabanubakode** [deepmind/acme#108]
Hi, I am trying to run r2d2 agent and it throws an error just after first episode is run: [reverb/cc/client.cc:159] Sampler and server are owned by the same process (21400) so Table priority_table is accessed directly without gRPC.
 and the program is later killed. 

Any idea why this is occurring and how can I get it to work?

Thanks!

**Comment by fastturtle** [comment]
Thanks for opening https://github.com/deepmind/reverb/issues/34, we will track this there.
