### ISSUE TITLE
Core Dumped on simple JAX DQN

### ISSUE THREAD

**Issue by fedetask** [deepmind/acme#113]
I'm trying acme with JAX and Haiku and I created a simple script that runs the JAX DQN agent:

```python
import acme
from acme.agents.jax import dqn
from acme import wrappers
import gym
import haiku as hk
import jax

env = wrappers.SinglePrecisionWrapper(wrappers.GymWrapper(gym.make('CartPole-v0')))
env_spec = acme.make_environment_spec(env)


def compute_q_values(state):
    q_net = hk.Sequential([hk.Linear(64), jax.nn.relu, hk.Linear(env_spec.actions.num_values)])
    return q_net(state)


forward_q = hk.without_apply_rng(hk.transform(compute_q_values))

dqn = dqn.DQN(env_spec, forward_q, batch_size=32, target_update_period=5, epsilon=0.05)
loop = acme.EnvironmentLoop(env, dqn)
loop.run(num_steps=5000)
``` 

The code seems to be running correctly (I get logs from `Learner` and `EnvironmentLoop`), but towards the end of training I get:
```commandline
[Learner] Steps = 5131
[Environment Loop] Episode Length = 200 | Episode Return = 200.0 | Episodes = 82 | Steps = 5189 | Steps Per Second = 221.168
terminate called without an active exception
Aborted (core dumped)
```

Am I doing something wrong in the end?

To add some context, I'm using 
```
jax                           0.2.13
jaxlib                        0.1.65+cuda112
tensorflow                    2.4.1
tfp-nightly                   0.13.0.dev20210512
```
The reason I'm using `tfp-nightly` instead of `tensorflow_probability` (that would be installed by `pip install dm-acme[tf]`) is that the latter is broken with JAX due to a new jax release (see [here](https://github.com/tensorflow/probability/issues/1289)).

**Comment by fastturtle** [comment]
Hi @fedetask, do you know if the  process finished training before the core dump?

We will be providing a new Acme release soon (hopefully later today), which uses nightly versions for TF, Reverb, and TFP. Perhaps you could try again when that comes out.

**Comment by fedetask** [comment]
I can confirm that the `loop()` terminates, therefore the core dumped does not happen within the call.

**Comment by fastturtle** [comment]
@fedetask are you still seeing this issue? Can you provide any additional logging output?

**Comment by qstanczyk** [comment]
Please reopen if this still causes problems.
