### ISSUE TITLE
Broken Link in README + Recommended Fix

### ISSUE THREAD

**Issue by RylanSchaeffer** [deepmind/acme#117]
The README's introductory paragraph has a link:

"Our [quickstart guide](https://github.com/deepmind/acme/blob/master/examples/quickstart) can be used to get running quickly. This notebook will show how to instantiate a simple agent and run it on an environment. You can also take a look at our tutorial, which takes a more in-depth look at the construction of the D4PG agent. This also highlights the general structure of most Acme agents which applies more broadly to all agents implemented in Acme."

That quickstart guide link is broken. It is currently https://github.com/deepmind/acme/blob/master/examples/quickstart but it should be https://github.com/deepmind/acme/blob/master/examples/quickstart.ipynb

**Comment by fastturtle** [comment]
Hi @RylanSchaeffer, thanks for reporting this issue. The link appears to be working correctly, is it still an issue for you?

**Comment by RylanSchaeffer** [comment]
Hi! I posted this issue before realizing I could message you internally on the Acme slack channel. Old habits, I suppose :)
