### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by Sheepsody** [deepmind/acme#12]
Hi,

Currently a master's student in France, I would like to contribute to your platform, which is exactly the project I was waiting to invest time on!

However, I haven't found any guidelines nor issues that could provide a starting point, and I saw in the paper that maybe new algorithms would be added in the future.

I am thus inquiring you (the maintainers) about possible points that I could tackle. I would be glad to add algorithms found in the literature, but starting with smaller issues would also be great.
You can contact me on victor.vialard@mines-paristech.fr if needed.

Thank you,

PS: Sorry if this message felt awkward...

**Comment by mwhoffman** [comment]
Hi! Not awkward at all. That's a great question! We'll be rolling out some additional guidelines very soon (think a week or so) and will include a few pointers for things that we think would be great to have but that we probably won't have time to look into. In the meantime take a look at the agents/examples we have now (which we will be adding more to, particularly examples!).

And I'll leave this issue open until we have a chance to send these guidelines out and will update you here.

**Comment by Sheepsody** [comment]
Hi! Thanks a lot for your answer.
I'm glad to know that you're giving opportunities to contribute to your platform.

**Comment by joaogui1** [comment]
Any idea when the guidelines will be posted @mwhoffman ?

**Comment by nikolamomchev** [comment]
Sorry for dropping this for so long. In the meantime contribution guidelines have been added here: https://github.com/deepmind/acme/blob/master/CONTRIBUTING.md
