### ISSUE TITLE
Is it possible to save a distributed D4PG model for reuse later?

### ISSUE THREAD

**Issue by Abinavraj5427** [deepmind/acme#123]
I'm actually a new to the acme framework. I am trying to figure out how to save the distributed d4pg model. In the example after ``lp.launch(program, lp.LOCAL_MULTI_PROCESSING)`` runs. 

In distributed learning there's often some sort of parameter server containing the updated network weights which the actors copy. Is there a way to obtain these network weights to save and rerun in the current acme framework after the model trains?

**Comment by nikolamomchev** [comment]
Please take a look at the savers in https://github.com/deepmind/acme/blob/master/acme/tf/savers.py and https://github.com/deepmind/acme/blob/master/acme/jax/savers.py

E.g. wrapping the learner in CheckpointingRunner would periodically persist its state and you can restore it after lp program is done. You can then use the Learner.get_variables method to extract the weights.
