### ISSUE TITLE
AttributeError: 'DQNAtariNetwork' object has no attribute 'init'

### ISSUE THREAD

**Issue by harshakokel** [deepmind/acme#126]
Hello, 

I am on ACME version `0.2.1` and Python version `3.8`. I am unable to run the DQN example from [examples/atari/run_dqn.py](https://github.com/deepmind/acme/blob/master/examples/atari/run_dqn.py).

I get `AttributeError: 'DQNAtariNetwork' object has no attribute 'init'` error. Has some one faced this issue?

**Comment by bshahr** [comment]
Hi harshakokel,

Is this still an issue? I can't seem to reproduce the error internally. If you're still getting this issue can you please reopen the issue and paste the stack trace here?

Thanks!

Bobak
