### ISSUE TITLE
Potential Tensorflow/Keras version Issue 

### ISSUE THREAD

**Issue by Sri-vatsa** [deepmind/acme#128]
I am trying to run one of the official notebooks. [Here](https://colab.research.google.com/github/deepmind/acme/blob/master/examples/tutorial.ipynb) is a copy of colab notebook with a weird error shown below. I have tried downgrading TF to 2.5.0 and 2.4.0 and this error goes away but a new issue comes up: LayerNormalization not found in Tensorflow. I am guessing it has something to do with the Keras version. Does anyone have suggestions for a fix? Thank you.

<img width="1315" alt="Screenshot 2021-06-17 at 11 48 40 PM" src="https://user-images.githubusercontent.com/17293409/122430885-8c583f80-cfc6-11eb-9af4-d54188fe2315.png">

**Comment by Sri-vatsa** [comment]
For anybody looking for a fix. What I have found to work is to comment out `pip install dm-acme[tf]` and install the relevant dependencies. Refer to the complete working repo for mountain car ![here](https://colab.research.google.com/drive/1ooz4fdRg60PGpZ8rJIZEhHsAWI9Hbtwu?usp=sharing)

**Comment by MichelangeloConserva** [comment]
They fixed the version mismatch in deepmind/acme@c7d3970d898c7b01be19d570a2740520984bc2e3.

For me, installing the latest nightly version of reverb and tensorflow2.6.0-dev20210619 worked.

**Comment by mwhoffman** [comment]
Hi Sri-vatsa. It sounds like you may have hit upon the same issue Michelangelo did and reported in https://github.com/deepmind/reverb/issues/51. The version mismatch should be working now after reverb's nightly updated, and we have the versions of these packages pinned to a known working combination at HEAD on github (the change https://github.com/deepmind/acme/commit/c7d3970d898c7b01be19d570a2740520984bc2e3 that Michelangelo notes). We'll push a similar update to pypi soon. Also, note that your solution solves this in a similar way, so thanks for the feedback!

I will close this issue as a result, but please reopen it if this crops up again. Thanks!
