### ISSUE TITLE
JAX agents depend on Sonnet

### ISSUE THREAD

**Issue by ethanluoyc** [deepmind/acme#129]
Hi, 

Currently, the reverb adders use utils from acme.tf, which imports Sonnet. This means that the user will not be able to use the JAX agents by with `pip acme[jax,reverb]`. I understand that reverb currently has a hard dependency on TensorFlow but it would be great if the dependency on Sonnet can be relaxed or added as part of the extra requirements for JAX.

Thanks!

**Comment by nikolamomchev** [comment]
Thanks for reporting this!

We have recently reworked the adders and in the process we have fixed this issue. We are still doing some final fixes but we hope to be able to release the new adders fairly soon.

**Comment by ethanluoyc** [comment]
Thanks!
Another somewhat related issue that I have posted earlier. This is about the adder not returning the correct types of fields when retrieving the batches.
https://github.com/deepmind/acme/issues/111

**Comment by ethanluoyc** [comment]
I can confirm that this issue is fixed. Close this.
