### ISSUE TITLE
Launchpad release?

### ISSUE THREAD

**Issue by rlanka4** [deepmind/acme#13]
Do you plan to release LaunchPad for distributed RL as well ?

**Comment by miriaford** [comment]
See my issue a few days ago #4 
TL;DR: they have no plans to release

**Comment by bshahr** [comment]
Yep, thank you miriaford! And thank you for the question rlanka4. We've now updated the FAQ to answer this.

**Comment by tomhennigan** [comment]
FYI Launchpad has been released (https://github.com/deepmind/launchpad, https://deepmind.com/research/open-source/launchpad) and distributed acme agents using launchpad were added in 3bc0426b.

**Comment by denfromufa** [comment]
@tomhennigan launchpad only for tf?

**Comment by tomhennigan** [comment]
@denfromufa launchpad works without tf.

**Comment by denfromufa** [comment]
@tomhennigan any example with jax?

**Comment by tomhennigan** [comment]
I am not aware of any, but I think many people use launchpad and JAX internally so I don't see you having any issues just using JAX inside one of your launchpad nodes.

I'd suggest filing a feature request on [deepmind/launchpad](https://github.com/deepmind/launchpad) if you want generic Launchpad+JAX examples or filing a new feature request on [deepmind/acme](https://github.com/deepmind/acme) if you want an ACME+JAX+Launchpad example.

**Comment by mwhoffman** [comment]
Exactly as @tomhennigan said: there are nothing stopping Launchpad+JAX and in fact we will be rolling out some examples very soon!

**Comment by wcarvalho** [comment]
Any updates on examples?
