### ISSUE TITLE
Can't use caches in distributed D4PG agent because `lp.CacherNode` is unavailable in open-sourced Launchpad

### ISSUE THREAD

**Issue by vaxenburg** [deepmind/acme#130]
The distributed D4PG agent won't work if `num_caches` is not zero in this line:
https://github.com/deepmind/acme/blob/master/acme/agents/tf/d4pg/agent_distributed.py#L43

This is because the `CacherNode` node type is unavailable in the open-sourced version of Launchpad. 
https://github.com/deepmind/acme/blob/master/acme/agents/tf/d4pg/agent_distributed.py#L239

**Comment by qstanczyk** [comment]
Indeed, Launchpad does not expose Cacher node externally at this point. We were hoping that the scale of external experiments wouldn't beyond the scale when cachers are needed.
