### ISSUE TITLE
Update Link for Quickstart Example in Document

### ISSUE THREAD

**Issue by PeppaCat** [deepmind/acme#135]
The link [here](https://github.com/deepmind/acme/tree/master/examples):
Our [quickstart](https://github.com/deepmind/acme/blob/master/examples/quickstart) guide can be used to get running quickly
should be:
https://github.com/deepmind/acme/blob/master/examples/quickstart.ipynb
instead of 
https://github.com/deepmind/acme/blob/master/examples/quickstart

**Comment by PeppaCat** [comment]
Also for this line just below the above.
 You can also take a look at our [tutorial](https://github.com/deepmind/acme/blob/master/examples/tutorial.ipynb). The original link is wrong.

**Comment by bshahr** [comment]
Fixed! Thanks for flagging :)
