### ISSUE TITLE
State based training

### ISSUE THREAD

**Issue by DriesSmit** [deepmind/acme#138]
Good day,

I am trying to implement an actor-critic algorithm with a state-based critic using the transition adder. I am trying to use extras to store the states of the environment, but I essentially need a state for each observation step. I see the transition adder provides the following data to the trainer:
`(s_t, a_t, r_t, d_t, s_{t+1}, e_t)`.

Where 's_t' and 's_{t+1}' are agent observations? I can use `e_t` to store the environment state, but this causes issues as I only have extras at timestep t, but actually need extras at timestep t and t+1. Or should I try to use 's_t' and 's_t+1' for the environment state and agent observation as well? Thanks for the help :)

**Comment by ethanluoyc** [comment]
I think it might be possible to use a SequenceAdder of length 2 instead of TransitionAdder for this task. In that case, you can put an extra for each time step.

**Comment by DriesSmit** [comment]
Thanks :+1: I did settle with using a SequenceAdder in the end. I had to adjust the SequenceAdder so that the extras align with the observations. So o_t and e_t is in sequence and not out by one.

**Comment by ethanluoyc** [comment]
I think so. If you look at the recurrent actors, you need to backtrack the last RNN states so that they are aligned with the time step.
