### ISSUE TITLE
Acme Tutorial Won't Start in Colab

### ISSUE THREAD

**Issue by mosicr** [deepmind/acme#14]
Hi, 
https://github.com/deepmind/acme/blob/master/examples/tutorial.ipynb
won't start in Colab. , if ran manually it fails on cell 2 with:
  File "<ipython-input-3-ea09e1624b41>", line 32
    except ModuleNotFoundError, OSError:
                              ^
SyntaxError: invalid syntax
Moreover, the Acme paper is full of typos and mistakes.

**Comment by mosicr** [comment]
Now in does open in Colab, but still fails with the above error.

**Comment by aslanides** [comment]
Hey mate. Thanks for pointing this out. Looking into it now :)

**Comment by aslanides** [comment]
I've made a fix which will get pushed in the next few minutes.

FWIW, our CI doesn't cover the colabs, so this is something we could improve.
