### ISSUE TITLE
Supported OSs

### ISSUE THREAD

**Issue by heho** [deepmind/acme#140]
Since ACME seems to need reverb to function and reverb does not work on Windows and appearantly MacOs, ACME does not support these OSs as well. This should be stated somewhere in the README.

**Comment by bshahr** [comment]
Hi heho,

Thanks for your comment! While we make heavy use of Reverb internally and in our open-sourced examples, the core Acme functionality seeks to be agnostic to your choice of replay system. If this is not the case, please re-open this issue with an example and we'll have a closer look.

Unfortunately I'm not aware of any examples of this so apologies for not being able to point you to anything more concrete. Hope you get it working and would love to hear more about your experience using Acme on different OSs!

Bobak
