### ISSUE TITLE
Custom evaluation metric 

### ISSUE THREAD

**Issue by B-Manel** [deepmind/acme#141]
Is there currently a way to add custom metrics for evaluation with Acme?

**Comment by bshahr** [comment]
Hi B-Manel,

Thanks for your question! You're definitely welcome to add any metrics you want to the learner outputs and those should be logged along with the others automatically. You can do a similar thing in the environment loop for actor/evaluator-side logging. In general you can view our agent implementations as examples that you can modify at will :)

I'll close this issue for now but do re-open if I misunderstood your question.

Bobak
