### ISSUE TITLE
Issues importing acme.tf

### ISSUE THREAD

**Issue by EvolvedSquid** [deepmind/acme#15]
Hi all,

Despite running: `pip install dm-acme[tf]`, using `import acme.tf` raises an error.  This appears to be an issue in both the Quickstart and Tutorial examples as well.

This is the reproducible code sample:
```
!pip install dm-acme
!pip install dm-acme[reverb]
!pip install dm-acme[tf]
!pip install dm-acme[envs]

import acme.tf
```

[Google Colab version](https://colab.research.google.com/gist/EvolvedSquid/619147b18400029ef5b7ebc034fefbba/acme-import-issue.ipynb)

**Comment by aslanides** [comment]
Hi. 

I'm not sure what you expect `import acme.tf` to do.

`acme.tf` is not a [module](https://docs.python.org/3/tutorial/modules.html), it's a [package](https://docs.python.org/3/tutorial/modules.html#packages); the __init__ file is [empty](https://github.com/deepmind/acme/blob/master/acme/tf/__init__.py). 

If you want to import e.g. the networks, you would do e.g. `from acme.tf import networks`, as we do in the examples.

**Comment by HuzzDTX** [comment]
Hi aslanides, 
I am running into a similar issue :

from acme.tf import networks

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-15-42f4d023524b> in <module>
----> 1 from acme.tf import networks

ModuleNotFoundError: No module named 'acme.tf

**Comment by EvolvedSquid** [comment]
I was also having issues importing the networks, but it looks like this is all solved in the latest patch.  Thank you!
