### ISSUE TITLE
quickstart.ipynb and tutorial.ipynb errors

### ISSUE THREAD

**Issue by Kenneth-Schroeder** [deepmind/acme#161]
Hi!
I am trying to get familiar with Acme for my master thesis.
Unfortunately, I can't get the example notebooks to work.

**QUICKSTART notebook**
When I run the quickstart notebook on colab line 6 of the import modules cell (`from acme.agents.tf import d4pg`) fails with `ImportError: This version of TensorFlow Probability requires TensorFlow version >= 2.7; Detected an installation of version 2.6.0. Please upgrade TensorFlow to proceed`.
I tried `!pip install tensorflow==2.7.0rc1` and the same line failed with `NotFoundError: /usr/local/lib/python3.7/dist-packages/reverb/cc/ops/libgen_reverb_ops_gen_op.so: undefined symbol: _ZN10tensorflow11ResourceMgr8DoCreateERKSsNS_9TypeIndexES2_PNS_12ResourceBaseE`.

**TUTORIAL notebook**
The same ImportError as described for the quickstart notebook appears here at line 8 of the import cell (`from acme.tf import networks`).

Appreciate your help, 
Best,
Kenneth

**Comment by qstanczyk** [comment]
0.2.3 PyPi version is out and it addresses the versioning problem (note that 'chex' still has to be installed by hand). Please reopen in case of problems.
