### ISSUE TITLE
JAX Actor core should use () for empty extras by default

### ISSUE THREAD

**Issue by ethanluoyc** [deepmind/acme#170]
Hi there,
I recently found an potential issue with the extra field in the actor core.
When there is no extra, I think the default returned here should match the default argument in `base.Adder`.
https://github.com/deepmind/acme/blob/master/acme/agents/jax/actor_core.py#L87

**Comment by nikolamomchev** [comment]
Can you explain is this a problem?

**Comment by ethanluoyc** [comment]
I am trying to implement a numpy-based replay and adders that know how to insert nested structures into this replay. When the extras is an empty tuple, handling the insertion by flattening the item with tree.flatten is straightforward as the empty tuple would not show up in the flattened list. If None is used, then None would appear in the flattened list and I have to add some extra handling for that case.

I guess this is a really minor problem. So feel free to close this.

**Comment by nikolamomchev** [comment]
I think there might be a benefit from being able to distinguish between "empty" and None.
Also, you can easily tweak the returned value to do what you want it to:

```
core = batched_feed_forward_to_actor_core(policy)
core.get_extras = lambda x: ()
```
