### ISSUE TITLE
Issue: PyPi package not containing all the Jax agents

### ISSUE THREAD

**Issue by cyprienc** [deepmind/acme#175]
Hi,

It looks like the PyPi package available [here](https://pypi.org/project/dm-acme/#files), doesn't contain all the Jax agents:
![content of the PyPi tarball](https://user-images.githubusercontent.com/5805228/144601014-0901b8d9-530f-4b4d-a377-aadc21d353d7.png)

How can I help adding them in?
Thanks,

Cyprien

**Comment by ethanluoyc** [comment]
I believe that the issue is that the newest 0.2.3 has not been uploaded on PyPI, right now to install the latest release you have to use pip install git+https://github.com/deepmind/acme@0.2.3. 

@qstanczyk Can you kindly upload the latest release version to PyPI as well?

**Comment by KaleabTessera** [comment]
@qstanczyk Just a ping on this incase you didn't see it. The pypi  package still points to acme 0.2.2 (https://pypi.org/project/dm-acme/).

**Comment by qstanczyk** [comment]
0.2.3 version is out now.
