### ISSUE TITLE
Any plan on open-sourcing JAX MPO?

### ISSUE THREAD

**Issue by ethanluoyc** [deepmind/acme#176]
Hi,

Similar to the request in https://github.com/deepmind/acme/issues/158, is there any plan to open source the JAX implementation of the MPO agent? This would be really useful since many DM papers build on top of MPO and it would be really useful to have an OSS version that the community can build on top of.

Best,
Yicheng

**Comment by nikolamomchev** [comment]
Hi @ethanluoyc, thanks for the question. Unfortunately we currently have no plans to open-source MPO.
