### ISSUE TITLE
ACME Quickstart tutorial unable to run

### ISSUE THREAD

**Issue by Tonyc-Water** [deepmind/acme#177]
Trying to tun the tutorial via Google Colab gives the following error in the 'Import Modules' part:

`ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-14-b1a2d0b81aef> in <module>()
      3 from acme import environment_loop
      4 from acme import specs
----> 5 from acme import wrappers
      6 from acme.agents.tf import d4pg
      7 from acme.tf import networks

3 frames
/usr/local/lib/python3.7/dist-packages/acme/jax/types.py in <module>()
     21 from acme import types
     22 from acme.utils import counting
---> 23 import chex
     24 import jax.numpy as jnp
     25 

ModuleNotFoundError: No module named 'chex'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------`

Seems like wrappers inside acme cannot be resolved. I read that something similar has happened before, see [here](https://github.com/deepmind/acme/issues/16).

I would appreciate help here.

Kind regards

Screeenshot:
![image](https://user-images.githubusercontent.com/37697227/145735141-976c6fec-ff88-4f46-8c4d-3af66f1e31e2.png)

**Comment by ethanluoyc** [comment]
You can probably avoid this problem by adding `!pip install chex`.

**Comment by Tonyc-Water** [comment]
Stack trace expanded:
![image](https://user-images.githubusercontent.com/37697227/145811020-2371a538-abac-4059-8e8b-33b3a13c66e2.png)

**Comment by ethanluoyc** [comment]
The violating line is:

https://github.com/deepmind/acme/blob/7c92b209b9e98d0571ace612a8277d5a610a0968/acme/wrappers/concatenate_observations.py#L65

If you add a definition like
```python
import tree
import numpy as np

def _zeros_like(nest, dtype=None):
  return tree.map_structure(lambda x: np.zeros(x.shape, dtype or x.dtype), nest)
```
and replacing the mentions of `utils.zeros_like` with _zeros_like
```python
dummy_obs = _zeros_like(observation_spec)
```
should solve the problem.

**Comment by Tonyc-Water** [comment]
After manually installing chex this error comes up:
![image](https://user-images.githubusercontent.com/37697227/145812634-7cae30a5-1007-4103-a53e-8a5ccfc85f50.png)

After manually installing launchpad the Import Modules step finishes successfully. Thanks for the help.

**Comment by Tonyc-Water** [comment]
Now this error happens, after relaunching the runtime to try a different environment:
![image](https://user-images.githubusercontent.com/37697227/145817049-65e9379d-e2c8-4dcb-9b9a-404e38c542f3.png)

It went through before. And after running the step again there is no error but when running the training loop this error happens:
![image](https://user-images.githubusercontent.com/37697227/145817443-9efbf6be-8903-45ac-b9ec-702c5042623a.png)

**Comment by Tonyc-Water** [comment]
I tried upgrading numpy, did not help.

This is the current error trying to run the training loop:
![image](https://user-images.githubusercontent.com/37697227/145821584-2f8ccfda-46e0-4c1d-aa4e-9e44c3266b66.png)

**Comment by Tonyc-Water** [comment]
AttributeError: module 'acme' has no attribute 'Learner' at "Import Modules" step

![image](https://user-images.githubusercontent.com/37697227/146451145-0508d1aa-198b-4d43-8fc2-d4e47ae05268.png)
