### ISSUE TITLE
dm-reverb problem with installation follow the Tutorial on MacOS 12

### ISSUE THREAD

**Issue by oxenoxeno** [deepmind/acme#179]
Collecting dm-reverb==0.6.1 (from dm-acme==0.2.4)
  Could not find a version that satisfies the requirement dm-reverb==0.6.1 (from dm-acme==0.2.4) (from versions: )
No matching distribution found for dm-reverb==0.6.1 (from dm-acme==0.2.4)

**Comment by ethanluoyc** [comment]
I think Reverb is for Linux only so you won’t be able to run on Macs
