### ISSUE TITLE
learner.step() error in tutorial.ipynb

### ISSUE THREAD

**Issue by kruthof** [deepmind/acme#182]
Hi! Running the tutorial I managed to construct the dataset and the learner. However, when running learner.step() I'm getting 

'TypeError: 'ParallelInterleaveDataset' object is not an iterator'

Despite that, a few function calls are outdated, e.g. 

- d4pg.D4PGLearner: argument 'dataset' instead of new: 'dataset_iterator'

**Comment by GarvinK** [comment]
it seems like initiating D4PGLearner with dataset_iterator = dataset.__iter__() could solve that problem. However, then I am get an ArttributeError:  'dict' object has no attribute 'discount' when calling learner.step(). I am getting a similar error when using DDPLearner with argument dataset=dataset.

**Comment by bshahr** [comment]
Hi kruthof,

Thanks for your question and apologies for the delay in getting back. Following the release of the new edition of Acme, along with new quickstart and tutorial guides, I'm going to mark this as closed.

Hope you like the new code and material! Happy Acming!

Bobak
