### ISSUE TITLE
Unable to import acme-quickstart modules.

### ISSUE THREAD

**Issue by Arcify** [deepmind/acme#184]
When running this part of the code from the quickstart jupyter notebook:

```
import IPython

from acme import environment_loop
from acme import specs
from acme import wrappers
from acme.agents.tf import d4pg
from acme.tf import networks
from acme.tf import utils as tf2_utils
from acme.utils import loggers
import numpy as np
import sonnet as snt
```

I get the error:

```
Traceback (most recent call last):

  File "C:\Users\User1\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-21-b1a2d0b81aef>", line 6, in <module>
    from acme.agents.tf import d4pg

  File "C:\Users\User1\anaconda3\lib\site-packages\acme\agents\tf\d4pg\__init__.py", line 17, in <module>
    from acme.agents.tf.d4pg.agent import D4PG

  File "C:\Users\User1\anaconda3\lib\site-packages\acme\agents\tf\d4pg\agent.py", line 23, in <module>
    from acme import datasets

  File "C:\Users\User1\anaconda3\lib\site-packages\acme\datasets\__init__.py", line 18, in <module>
    from acme.datasets.reverb import make_reverb_dataset

  File "C:\Users\User1\anaconda3\lib\site-packages\acme\datasets\reverb.py", line 22, in <module>
    from acme.adders import reverb as adders

  File "C:\Users\User1\anaconda3\lib\site-packages\acme\adders\reverb\__init__.py", line 20, in <module>
    from acme.adders.reverb.base import DEFAULT_PRIORITY_TABLE

  File "C:\Users\User1\anaconda3\lib\site-packages\acme\adders\reverb\base.py", line 27, in <module>
    import reverb

  File "C:\Users\User1\anaconda3\lib\site-packages\reverb.py", line 64
    raise TypeError, 'Regexp cannot be negated'
                   ^
SyntaxError: invalid syntax
```

but I do not understand at all why I get this error. I tried to pip install reverb, but that did not fix the bug. 

Furthermore, I expect that this error is related to the warning I get when installing Acme:

`WARNING: dm-acme 0.2.4 does not provide the extra 'reverb'`

I would really appreciate it if someone were able to help me fix this issue.

The python version I am using is Python 3.8.5

**Comment by qstanczyk** [comment]
If you want to install reverb you need to install `pip install dm-acme[tf]` for example.

**Comment by Arcify** [comment]
> If you want to install reverb you need to install `pip install dm-acme[tf]` for example.

I had done that, that was also in the quickstart notebook

**Comment by qstanczyk** [comment]
C:\Users\User1\anaconda3\lib\site-packages\reverb.py looks suspicious. Do you have some other reverb installed? Maybe `pip install reverb`? (`pip install dm-reverb` is used by Acme).

**Comment by Arcify** [comment]
> C:\Users\User1\anaconda3\lib\site-packages\reverb.py looks suspicious. Do you have some other reverb installed? Maybe `pip install reverb`? (`pip install dm-reverb` is used by Acme).

@qstanczyk When i try `pip install dm-reverb` I get 
```
ERROR: Could not find a version that satisfies the requirement dm-reverb (from versions: none)
ERROR: No matching distribution found for dm-reverb
```
And I indeed also have `pip install reverb` installed but I just deinstalled it and tried it again but it still gives the same errors

**Comment by qstanczyk** [comment]
Looks like Reverb is not available for your platform. See [here](https://github.com/deepmind/reverb#installation).

**Comment by Arcify** [comment]
> Looks like Reverb is not available for your platform. See [here](https://github.com/deepmind/reverb#installation).

@qstanczyk I am indeed not using "Linux", does that mean I can not use acme in general because reverb is only supported for linux?

**Comment by qstanczyk** [comment]
You can use Acme through Docker on Window.

**Comment by Arcify** [comment]
Okay thank you for your time I will try that out @qstanczyk 

> You can use Acme through Docker on Window.

**Comment by mgiammar** [comment]
@qstanczyk I am getting the same error when importing reverb.

```
>>> import reverb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/User1/opt/anaconda3/lib/python3.8/site-packages/reverb.py", line 64
    raise TypeError, 'Regexp cannot be negated'
```

However, I'm on MacOS and naively think Unix is close enough to Linux. Do I also need to run through Docker?

**Comment by qstanczyk** [comment]
It's not unfortunately. See [here](https://pypi.org/project/dm-reverb/#files)
