### ISSUE TITLE
Set tf.Dataset for maximum performance

### ISSUE THREAD

**Issue by markub3327** [deepmind/acme#186]
Hi,
  Can I set `num_parallel_calls` to `os.cpu_count()` for getting the maximum performance?

Thanks.

My code:
```python
    def make_reverb_dataset(server_address: str, table: str, batch_size: int, num_parallel_calls: int = None):
        if num_parallel_calls is None:
            num_parallel_calls = os.cpu_count()
    
        def _make_dataset(unused_idx):
            dataset = reverb.TrajectoryDataset.from_table_signature(
                server_address=server_address,
                table=table,
                max_in_flight_samples_per_worker=(2 * batch_size),
            )
    
            dataset = dataset.batch(batch_size, drop_remainder=True)
    
            return dataset
    
        # Create the dataset
        dataset = tf.data.Dataset.range(num_parallel_calls)
        dataset = dataset.interleave(
            map_func=_make_dataset,
            cycle_length=num_parallel_calls,
            num_parallel_calls=num_parallel_calls,
            deterministic=False,
        )
        dataset = dataset.prefetch(tf.data.AUTOTUNE)
    
        return dataset
```

**Comment by nikolamomchev** [comment]
@markub3327 I am not sure if this will help. In our experience [this](https://github.com/deepmind/acme/blob/master/acme/agents/jax/sac/builder.py#L125) was performant enough to not be the bottleneck for the algorithm.

If you want to get the maximum performance, here's few things that you should look at:
1. If learning is the bottleneck, try increasing [num_sgd_steps_per_step](https://github.com/deepmind/acme/blob/master/acme/agents/jax/sac/agents.py#L131)
2. If collecting experience is the bottleneck, try running distributed algorithm with multiple actors (see [DistributedSAC](https://github.com/deepmind/acme/blob/master/acme/agents/jax/sac/agents.py#L37) is a good example to start with).

**Comment by markub3327** [comment]
@nikolamomchev 

   here is an efficient solution: https://github.com/deepmind/reverb/issues/90. I asked directly deepmind/Reverb team.
