### ISSUE TITLE
Dead paper link in blog post

### ISSUE THREAD

**Issue by drozzy** [deepmind/acme#19]
Here: https://deepmind.com/research/publications/Acme it links to here (at the bottom):
https://github.com/deepmind/acme/blob/master/paper.pdf

**Comment by guskal01** [comment]
Link still not working for me, extra space (%20) at the end of the link.

**Comment by drozzy** [comment]
Yap, can confirm it links wrong: https://arxiv.org/abs/2006.00979%20

**Comment by drozzy** [comment]
I found a nifty chrome extension that will automatically show you broken links:
![Screenshot from 2020-06-17 17-56-15](https://user-images.githubusercontent.com/140710/84954693-dfea3180-b0c3-11ea-965b-7f336c5ca66a.png)

**Comment by bshahr** [comment]
Thanks drozzy and guskal01!
