### ISSUE TITLE
Delaying critic target update in TD3?

### ISSUE THREAD

**Issue by ethanluoyc** [deepmind/acme#195]
Hi,

When looking at the TD3 JAX agent, I found an implementation difference in how the target critic is updated. In the original repo, the target network is updated delayed similar to how the policy network target is delayed. I have created a PR #194 that tries to match this detail in the original repo. 

I am not sure if this makes any difference empirically or it's worth trying to match this detail, feel free to close this issue and #194 if you think this is not necessary. I am mostly making a note of what I found here in case someone is interested in knowing this difference.

**Comment by ddsh** [comment]
Hi,

Thanks for pointing this out. I ran some experiments on locomotion tasks and found that the current implementation get slightly better results. I'll go and add a comment to make sure the difference with the authors' implementation is emphasized.

Cheers

**Comment by ethanluoyc** [comment]
Thanks!
I suspect this is also better. In the current approach, the critic is likely to be more accurate, thus the performance would be better. Good to know that empirical evidence backs this up :D
