### ISSUE TITLE
for windows

### ISSUE THREAD

**Issue by Clown1206** [deepmind/acme#196]
Hello,  I am a college student and I have come into contact with acme. Can't acme run on Windows system?

**Comment by ethanluoyc** [comment]
Hi, I think unfortunately it's not possible. The problem is that some of the dependencies is Linux only (e.g. Reverb, Acme's replay buffer system, which is not even compatible with Mac).

**Comment by Arcify** [comment]
You run acme on the Docker platform

**Comment by Clown1206** [comment]
> You run acme on windows via the Docker platform, but otherwise indeed many dependencies can not be installed on Windows
Thank you for your reply. Can Acme run on Ubuntu? If so, which version of Ubuntu do I need to install?(maybe Ubuntu 18.04.1 LTS？)

**Comment by Arcify** [comment]
> > You run acme on windows via the Docker platform, but otherwise indeed many dependencies can not be installed on Windows
> > Thank you for your reply. Can Acme run on Ubuntu? If so, which version of Ubuntu do I need to install?(maybe Ubuntu 18.04.1 LTS？)
Yes, acme can definitely run on Ubuntu, I am not sure which versions work and don't however I expect most recent versions to work, one I have personally used is Ubuntu 20.04.3 LTS which worked.

**Comment by nikolamomchev** [comment]
Thanks @ethanluoyc and @Arcify for your answers.

@Clown1206 Acme should work fine with the most modern linux installations (including Ubuntu) and indeed I don't think you can easily run it on Windows. Please give it a try and let us know if you encounter problems.
