### ISSUE TITLE
AttributeError: module 'reverb' has no attribute 'Client'

### ISSUE THREAD

**Issue by Clown1206** [deepmind/acme#197]
Hello，when I run dqn I get an error saying "AttributeError: module 'reverb' has no attribute 'Client' " The program statement located is : client: reverb.Client,（I'm using windows10 ）

**Comment by qstanczyk** [comment]
Reverb doesn't support Windows platform, so DQN agent can't run there.

**Comment by Clown1206** [comment]
> Reverb doesn't support Windows platform, so DQN agent can't run there.

Thank you. Maybe I should use the Linux platform?
