### ISSUE TITLE
signature input in reverb.Table()

### ISSUE THREAD

**Issue by DailiZhang2010** [deepmind/acme#200]
Can someone help provide an example of 
replay_buffer = reverb.Table(
    name=adders.DEFAULT_PRIORITY_TABLE,
    max_size=1000000,
    remover=reverb.selectors.Fifo(),
    sampler=reverb.selectors.Uniform(),
    rate_limiter=reverb.rate_limiters.MinSize(min_size_to_sample=1),
    signature=????)
Looks like now signature needed to be defined in the reverb.Table to make the tutorial work?
Can someone help provide an example of what the signature input shall look like?

**Comment by nikolamomchev** [comment]
@DailiZhang2010 Normally you can obtain this with the `Adder.signature()` class method of the adder you are using.
For examples, check out the `make_replay_tables` method in any of the jax builders (e.g. https://github.com/deepmind/acme/blob/master/acme/agents/jax/ppo/builder.py#L58 and https://github.com/deepmind/acme/blob/master/acme/agents/jax/td3/builder.py#L120).

Please close the issue if this resolves your question.

**Comment by qstanczyk** [comment]
Please reopen if there are any outstanding questions / problems.
