### ISSUE TITLE
Contributing IQL and TD3-BC JAX implementation.

### ISSUE THREAD

**Issue by ethanluoyc** [deepmind/acme#204]
Hi Acme developers,

Is there any interest in including two more offline RL learner in the official Acme repo? I have currently implemented both of them at  https://github.com/ethanluoyc/magi and if there's interest, I can contribute these back to the Acme repo.

**Comment by nikolamomchev** [comment]
Hi @ethanluoyc,

Thank you for offering to contribute to those!

In the meantime we've added an option to TD3 to run TD3+BC.
You can find an example here: https://github.com/deepmind/acme/blob/master/examples/offline/run_offline_td3_jax.py

We have also added ability to reproduce https://arxiv.org/pdf/2106.08909.pdf in CRR [example](https://github.com/deepmind/acme/blob/305aaf91f3728bd28cd3d851dd36c9d4a581eb26/examples/offline/run_crr_jax.py#L52).

If you are interested, please those a try and let us know what you think.

Regarding IQL: While we agree that this would be a great algorithm to have in Acme, we've discussed this internally and we feel that supporting externally contributed algorithms can be tricky for us and we can't commit to it. However, if this would help your project, be open to adding a "friends of Acme" section in our documentation and linking magi's CQL from there (reserving the right to remove the link if we ever decide to implement CQL inside Acme). Let me know what you think about this.

**Comment by ethanluoyc** [comment]
Thanks for letting me know! Yeah, I can understand that accepting external agent contributions will create maintenance problems so it does look like a good idea for me to keep them in magi. Adding a section in the documentation sounds like a good plan! Let me try to create a PR for that.

Regarding CRR. It seems that the JAX version of CRR is not yet open-sourced. I do also have them implemented in magi as well, but it would be great if you can share your Acme's CRR implementation. I have found that it's difficult to get CRR to work well on the D4RL benchmark, and I have wondered if I have implemented things differently.

**Comment by nikolamomchev** [comment]
@ethanluoyc FYI, CRR is now open-sourced.

**Comment by ethanluoyc** [comment]
@nikolamomchev Awesome! Thanks a lot!
