### ISSUE TITLE
State of JAX support? 

### ISSUE THREAD

**Issue by IanQS** [deepmind/acme#210]
From the online documentation it seems like the state of JAX support is still significantly behind TF. is this documentation correct and if so are there any plans to update Acme to have better Jax support?

**Comment by wookayin** [comment]
https://github.com/deepmind/acme/tree/master/examples seems outdated. Although I am not a ACME/DM member, I don't think JAX support is behind TF as it has been quite while since DM has completely changed and moved to JAX ecosystem. What JAX support specifically are you looking for?

**Comment by wookayin** [comment]
Yes those docs are not updated nor well maintained. You can find the up-to-date list of JAX and TF agents available in the code repository:

https://github.com/deepmind/acme/tree/master/acme/agents/jax
https://github.com/deepmind/acme/tree/master/acme/agents/tf

Indeed there are more JAX agents. JAX has the primary support now (you should expect no more TF supports and updates)

**Comment by IanQS** [comment]
Thank you! I just wanted to make sure I didn't build something off a minimally supported backend. 

Closing the issue
