### ISSUE TITLE
Sharp edges when used in production environments (Jax) 

### ISSUE THREAD

**Issue by IanQS** [deepmind/acme#211]
Hey there!

I was just wondering if there are any sharp edges to watch out for? I'm interested in using this to experiment with and eventually using it to deploy to a prod env

**Comment by nikolamomchev** [comment]
Hi Ian, we don't have a list of know "sharp edges". Please give it a try and let us know if you hit any.

One thing that comes in mind is that this is  a research-oriented framework. As such, we reserve the right to make backward-incompatible changes without advance warning. Having said that, we are committed to make sure our agents will continue to work and perform well (e.g. we are actively working on setting up a regression testing framework).
