### ISSUE TITLE
Start distributed agent acting __after__ compilation

### ISSUE THREAD

**Issue by wcarvalho** [deepmind/acme#212]
Hello,

First, amazing codebase.

I have an agent that takes longer to compile than other agents (20 minutes vs 10 minutes). Is it possible to have the distributed agent wait until compilation to start acting? It's otherwise challenging to compare the results since they start learning at different points in the data sampling process.

Thank you!

**Comment by nikolamomchev** [comment]
@wcarvalho thanks for the nice words! We are very happy you find it useful!

In general with distributed setups it is hard to control the exact time when actors and learners start acting. However, Reverb's rate limiters allow for some control on when learning starts. E.g. take a look at how DQN sets up the rate limiter for Reverb:
http://google3/third_party/py/acme/agents/jax/d4pg/builder.py?l=84

```
    limiter = rate_limiters.SampleToInsertRatio(
        min_size_to_sample=self._config.min_replay_size,
        samples_per_insert=self._config.samples_per_insert,
        error_buffer=error_buffer)
```

This would guarantee that:
1) the learner will only sample from the replay table once it has at least `min_replay_size` elements.
2) the ratio of inserts to samples from Reverb is within some limits of the specified number. 

Would this be enough for you to guarantee that results from different agents are comparable?

**Comment by wcarvalho** [comment]
Thank you! This should work :)
