### ISSUE TITLE
Some dependencies missing in quickstart

### ISSUE THREAD

**Issue by drozzy** [deepmind/acme#22]
Finally got it running! Works great guys. Looking forward to using this in the future.

The only issue I encountered was that running the [quickstart](https://github.com/deepmind/acme/blob/master/examples/quickstart.ipynb) example notebook failed due to (a lot of) missing dependencies.

I hunted them down and made a sample project that includes all of the necessary dependencies in a conda [environment.yml](https://github.com/drozzy/acme_rl_example/blob/master/environment.yml) file:

https://github.com/drozzy/acme_rl_example

(I omitted jax because I've never used it and mujoco because I didn't need it).

Some new users may find it useful. I also suggest you provide a conda environment file for people instead of pip instructions, as it is much more reliable/reproducible.

**Comment by aslanides** [comment]
Hi drozzy. Thanks for doing this! One thing, I can't see the repository you linked; is it private?

**Comment by drozzy** [comment]
Sorry forgot to make it public. Should be fixed now.

**Comment by drozzy** [comment]
Type hints are awesome in the code. It's very easy to read!

**Comment by JeffT13** [comment]
Hey drozzy. Thank you for this it has been very helpful as new user. I seem to be running into an issue while attempting to get all the dependencies running and using your env and was wondering if you might have any insight. Specifically I'm having an issue importing reverb after building the conda env. I get 

"ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory" 

Im running Ubuntu 20.04 LTS on Windows Subsystem for Linux 2 and all other packages not dependent on reverb import properly. Thank you for your time.

**Comment by brianmusuku** [comment]
If you still get the error:
"ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory"

after `sudo ldconfig /home/usr/anaconda3/lib`

run `sudo apt-get install libpython3.7`

**Comment by brianmusuku** [comment]
Also I found that the stable tensorflow-probability (0.10.1) has an error:
"" ImportError: cannot import name 'naming' from 'tensorflow.python.autograph.core'""
Fix this by installing the nightly build
`pip install tfp-nightly 0.11.0.dev20200708`

**Comment by qstanczyk** [comment]
Please re-open if this is still an issue for you.
