### ISSUE TITLE
Maximum number of steps ignored and program doesn't terminate

### ISSUE THREAD

**Issue by wcarvalho** [deepmind/acme#222]
I've noticed that sometimes, the maximum number of steps are reached but the program doesn't terminate? This makes it very challenging to automate running experiments.

You can see timestamps below. 
![image](https://user-images.githubusercontent.com/6220222/163721671-24343eac-0608-466e-bee3-e56aa8c02e8d.png)

![image](https://user-images.githubusercontent.com/6220222/163721677-d24b3953-e3a5-4333-9aa5-ff6e2be6391b.png)

**Comment by sinopalnikov** [comment]
Hi Wilka,
what script are you using to launch the program?
If you can give us the command line as well, that would help.

**Comment by wcarvalho** [comment]
I'm using a custom builder that's a **very close** replica of [R2D2](https://github.com/deepmind/acme/blob/45bd2de8f7e9c5f9efa762f165293c10bde01402/acme/agents/jax/r2d2/agents.py#L36).

One thing to note is that I launch multiple runs using the [Ray](https://docs.ray.io/en/latest/) toolkit for running multiple jobs.  Ray will launch the program in a sub-process. I'm not sure if that's part of the problem?

**Comment by wcarvalho** [comment]
I think it's related to running multiple jobs at the same time. I think that when JOB1 calls `lp.stop()`, it might cancel processes for JOB2 (e.g. the coordinator), leading JOB2 to have running processes which are never killed?

**Comment by nikolamomchev** [comment]
I'm not very familiar with Ray but it may be due to the way ray and LaunchPad interact.

Did you know that you could pass multiple programs as a list to `lp.launch`? Would this allow you to do what you need purely with LP?

**Comment by qstanczyk** [comment]
Are JOB1 and JOB2 started from the same process? If so then `lp.stop()` can be the problem indeed (as it uses signals to notify launching process to terminate started program(s)). But if Ray starts a code that calls `lp.launch` in a new process then this shouldn't be the problem.

**Comment by qstanczyk** [comment]
Please reopen in case of any follow-up questions.
