### ISSUE TITLE
lp.launch error: psutil.NoSuchProcess process no longer exists (pid=499)

### ISSUE THREAD

**Issue by kmukeshreddy** [deepmind/acme#225]
The below code is giving me an error when the max_actor_steps is reached by the program.
Due to this, I am not able to launch another new tmux launchpad session.
Any suggestion to fix this issue?

**Error:** 
psutil.NoSuchProcess process no longer exists (pid=499)

**Code:**
lp.launch(program, lp.LaunchType.LOCAL_MULTI_PROCESSING)

start = datetime.now()
try:
  !tmux a -t "launchpad"
except Exception as e:
  print(e)
  !tmux kill-session
  pass 
stop = datetime.now()
runtime = stop - start
print('Total run time: {} (HH:MM:SS)'.format(runtime))
print('-'*20)

Note: I am running it in the colab notebook.

Other error:
Timeout (10000 ms) exceeded when flushing the writer before deleting it. Caught Reverb exception: Flush call did not complete within provided timeout of 0:00:101;24r23;1H1;23r23;80H

**Comment by kmukeshreddy** [comment]
Hi,

Any comments?

or Is there anything that I am doing wrong?

**Comment by qstanczyk** [comment]
psutil.NoSuchProcess is a Python exception, so there should be a stack trace available pointing at the location of the problem. Could you post it here?

**Comment by kmukeshreddy** [comment]
attaching the stack trace:

```
I0523 14:45:50.074655 139772326725504 terminal.py:91] [Actor] Actor Episodes = 201 | Actor Steps = 6030 | Episode Length = 30 | Episode Return = 116.01786804199219 | Evaluator Episodes = 986 | Evaluator Steps = 29580 | Learner Steps = 6742
| Learner Walltime = 49.165 | Steps Per Second = 101.214

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/launchpad/launch/worker_manager.py](https://localhost:8080/#) in _signal_dispatcher(sig, frame)
     60       try:
---> 61         dispatcher(sig, frame)
     62       except TypeError:

TypeError: _stop_or_kill() takes 1 positional argument but 3 were given

During handling of the above exception, another exception occurred:

NoSuchProcess                             Traceback (most recent call last)
8 frames
[/usr/local/lib/python3.7/dist-packages/psutil/__init__.py](https://localhost:8080/#) in wrapper(self, *args, **kwargs)
    281     def wrapper(self, *args, **kwargs):
    282         if not self.is_running():
--> 283             raise NoSuchProcess(self.pid, self._name)
    284         return fun(self, *args, **kwargs)
    285     return wrapper

NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=529)
```

**Comment by qstanczyk** [comment]
I think [this](https://github.com/deepmind/launchpad/commit/89613dc5ada4afec1006a44fc24682f253fdea4d) might help.

**Comment by qstanczyk** [comment]
Please reopen if it doesn't
