### ISSUE TITLE
Regarding controlled runs for D4PG lp.launch

### ISSUE THREAD

**Issue by kmukeshreddy** [deepmind/acme#226]
Hi, 

In D3PG, we have control over the Runs.
First, the learner will learn for n episodes/ loops, then the evaluator loop is executed.

**D3PG Code:**
train_loop = acme.EnvironmentLoop(environment, agent, label='train_loop', logger='train_logs')
train_loop.run(num_episodes=20,000)
eval_loop = acme.EnvironmentLoop(eval_env, eval_actor, label='eval_loop', logger='eval_logs')
eval_loop.run(num_episodes=5000)

**Questions:**
1. How can we achieve the same thing in the D4PG? like running the learner for 20,000 episodes and then running the evaluator for 5000 episodes?
2. How to pass the custom logger path for training and evaluation in D4PG?

**Comment by qstanczyk** [comment]
Please have a look at [this example](https://github.com/deepmind/acme/blob/master/examples/baselines/rl_continuous/run_d4pg.py). It should provide you with an insight on how to configure evaluation frequency. Regarding logging - [experiment config](https://github.com/deepmind/acme/blob/ef63ed8b5d6d428adef90c70761c87485898bb98/examples/baselines/rl_continuous/run_d4pg.py#L67) constructed in this example can be configured with a custom logger factory - you can do whatever you want there.

**Comment by qstanczyk** [comment]
Please reopen if you have any further questions.

**Comment by kmukeshreddy** [comment]
Hello, Apologies for the late update.

I have looked into the links which you provided. The reference is for the Jax framework.
I am looking for Tensorflow implementation, but I couldn't find it.

Please let me know, where I could find the Tensorflow reference.

**Comment by qstanczyk** [comment]
Tensorflow agents are not maintained/supported anymore, sorry.
