### ISSUE TITLE
Callback system

### ISSUE THREAD

**Issue by schouhy** [deepmind/acme#24]
Hi everyone!
Thank you for sharing this project.
I have a few ideas that I think might contribute to your library and before making a pr I thought of asking here first to check if you are interested.

The idea would be to take one more abstraction step and instead of having an Agent with an Actor and a Learner, an Agent would have an Actor and a list of Callbacks. The Learner would be itself a Callback, but also the Adder, the Logger, and even the Noise. The Callbacks would react at certain events similar to fastai callback system ('on_episode_begin', 'on_episode_end', 'on_feedback', 'before_select_action', 'after_select_action').
Callbacks may be disabled on demand. So after running the the env_loop, one could simply call `agent._noise.disable()` to remove noise.
The environment loop looks quite clearner this way too:

```python
iterator = range(num_episodes) if num_episodes else itertools.count()

for _ in iterator:
    timestep = self._environment.reset()

    self._callbacks.call('on_episode_begin', timestep=timestep)

    # Run an episode.
    while not timestep.last():
        # Generate an action from the agent's policy and step the environment.
        action = self._agent.select_action(timestep.observation)
        timestep = self._environment.step(action)

        self._callbacks.call('on_feedback', action=action, next_timestep=timestep)

    self._callbacks.call('on_episode_end')
```
I forked your repo and started implementing it (it is actually almost done). It involves quite a few changes, so let me know if you would be willing to take a look at it.

**Comment by drozzy** [comment]
Note: I'm not a contributor, just a random user.

I, personally, appreciate the lack of callbacks (callback hell). Makes code much easier to read.

But even if you wanted callbacks, wouldn't it just be another class similar to EnvironmentLoop?:
https://github.com/deepmind/acme/blob/f8867fe383c591d00f873323b308cd4e70f9f818/acme/environment_loop.py#L30

**Comment by schouhy** [comment]
Hi! No, callbacks would be part of agents (much like actors and learners). The environment could also have its own callbacks like logs and so, but that's not the part I'm really interested in.

**Comment by miriaford** [comment]
I'm also not a contributor, but I personally agree with @drozzy: callbacks can easily become sprawling code that reduces readability, even though they are supposed to be clean abstractions. 
That being said, not all callbacks are bad - I'd love to see how you actually implement it @schouhy. Is there a public fork?

**Comment by schouhy** [comment]
I'm still working on it but here it is https://github.com/schouhy/acme/tree/callback_refactor
Let me know your thoughts!

**Comment by aslanides** [comment]
Hi schouhy, thanks for the interest! I haven't yet looked at your proposal in detail. Can you explain what problem it is you're trying to solve?

**Comment by fastturtle** [comment]
Hey schouhy, thanks for bring in new ideas, always exciting to see new perspectives!

I personally find callbacks to be tricky since they introduce informal API requirements that tend to make the codebase more difficult to understand. That said, the idea of introducing an `Observer` class, and a list of observers that is passed into the `EnvironmentLoop` does come up every now and then. The observers sit between the actor and environment, and receive data about the interactions between them (observers should **not** mutate any data). I believe this would be very similar to your `'on_feedback'` callback. However I feel that these observers would almost always be used for logging (our loggers are basically observers), in which case calling them loggers and limiting their scope is more explicit.

**Comment by schouhy** [comment]
Thank you guys for the prompt replies!

@aslanides I guess I'm not addressing any specific problem. My proposal is to keep going in the same direction you already took and further divide agents into building blocks that run independently. The benefits of it would be more flexibility to turn on and off certain functionality of the agent and the ability to add new ones even for already trained agents. This way the environment loop could also be easily used not only to train but also to evaluate the agent, just by disabling the learner, the noise, the adders, and by enabling bookkeeping of the steps and rewards. I imagine this could be a nice feature to have while running experiments.

@fastturtle I agree Observers would mainly be for logging, but I believe adders could also be observers and there could be observers that do the bookkeeping of rewards in an evaluation stage and provide nice plots, or also bookkeep metrics about the weights of the networks in a train stage. It may be a healthy refactor anyway.

Let me know your thoughts! And if callbacks are really off the table for you, then feel free to close the issue.

**Comment by TheSnowGuru** [comment]
Hey guys, I created a discord for this project to be able to better contribute to the issues,share training results and more,  enjoy. 
https://discord.gg/Rf6EU7

**Comment by nikolamomchev** [comment]
Coming back to this thread, the `EnvironmentLoop` now can be configured with an observer:
https://github.com/deepmind/acme/blob/master/acme/environment_loop.py#L66
