### ISSUE TITLE
Issue when import acme

### ISSUE THREAD

**Issue by JiaojiaoYe1994** [deepmind/acme#240]
Hi everyone, when I try to import acme module, I have met the following problem, does anyone has the same issue and please tell me how to solve it.

* Execution
`from acme import environment_loop`

* Error
```
File "/home/acme/acme/specs.py", line 36
    observations: Any
                ^
SyntaxError: invalid syntax```

**Comment by ethanluoyc** [comment]
Are you using Python 2? I think Acme is Python3 only

**Comment by qstanczyk** [comment]
that is correct, Acme is Python 3 only. Please reopen if you are using Python 3 and hitting this issue.
