### ISSUE TITLE
How to use in "production"?

### ISSUE THREAD

**Issue by sguysc** [deepmind/acme#244]
I'm looking for the right way to use a trained agent (e.g. d4pg) after it has been taught.
I could not see an example where the agent is being loaded from disk.

What I currently do, with limited success, is save the trained weights for the networks (policy, critic)
using `acme.tf.savers.pickle.dump()` the objects. Then, at test time, I use the load method to 
get the trained network and re-create the agent object with the main difference of
changing `sigma=0` so I'll have deterministic actions.

**I experienced two problems:**
 a. It is still not 100% deterministic, calling the `select_action` with the same
observations yields ever-so-slightly different action outputs.
 b. And this may be attached to (a), I feel like the agent is still learning, or maybe taking "something" 
from a different place than the pickled files. The reason is that it prints outputs to the screen 
about loading checkpoints from temporary folders, even though `checkpoint=False`, and second, because
even though I had a working weight file and did not mess with them, at some point the agent was not
doing well at all and I had to re-train.
```
[reverb/cc/platform/tfrecord_checkpointer.cc:150]  Initializing TFRecordCheckpointer in /tmp/tmp9ulhynov.
[reverb/cc/platform/tfrecord_checkpointer.cc:386] Loading latest checkpoint from /tmp/tmp9ulhynov
```

So my question is - what is the right way to load agents, not use them right after training, and enforce no learning and deterministic outputs?

I basically use the [quickstart example](https://github.com/deepmind/acme/blob/master/examples/quickstart.ipynb) with the moutaincar.
```python
# when training
agent = d4pg.D4PG(
    environment_spec=environment_spec,
    policy_network=policy_network,
    critic_network=critic_network,
    observation_network=observation_network,
    sigma=1.0,
    logger=agent_logger,
    checkpoint=False
)
...
with open('critic_network.w', 'wb') as dbfile:
    savers.pickle.dump(critic_network,dbfile)

# when loading
with open('critic_network.w', 'rb') as dbfile:
    new_critic_network = savers.pickle.load(dbfile)
new_agent = d4pg.D4PG(
    environment_spec=new_environment_spec,
    policy_network=new_policy_network,
    critic_network=new_critic_network,
    observation_network=new_observation_network,
    sigma=0.0, #no exploration now
    checkpoint=False
)
```

**Comment by qstanczyk** [comment]
I would suggest trying out [Snapshotter](https://github.com/deepmind/acme/blob/master/acme/jax/snapshotter.py). It is used by [make_distributed_experiment](https://github.com/deepmind/acme/blob/0af4090dbff4784471e589843676187ea5f2720d/acme/jax/experiments/make_distributed_experiment.py#L260). [Instructions](https://www.tensorflow.org/guide/saved_model) on how to use SavedModel. Hope that helps.

**Comment by sguysc** [comment]
Thank you.
How do I prevent changes to the networks when used for testing?

**Comment by qstanczyk** [comment]
What changes to the network do you mean? You should be able to load the model independently of Acme codebase and use it to perform inference only.

**Comment by sguysc** [comment]
As I wrote, I load the weights, connect to the gym environment and re-create the agent object
```python
new_agent = d4pg.D4PG(
    environment_spec=new_environment_spec,
    policy_network=new_policy_network,
    critic_network=new_critic_network,
    observation_network=new_observation_network,
    sigma=0.0, #no exploration now
    checkpoint=False)
```
Then, I reset the environment, and call `new_agent.select_action(z_i)` where `z_i` is the observation of the first state. I get some action A for the first time step. Then, run it again keeping the observation **constant**, and get a slightly different action A+eps. I assume something in the NN is still updating somehow, or is it something else? I'd like that for a given observation, the output action will be the same.

**Comment by sguysc** [comment]
Thank you, it works!
To be more specific for future searchers, 
```python
from acme.agents.tf.actors import FeedForwardActor
with open('policy_network.w', 'rb') as dbfile:
    new_policy_network = savers.pickle.load(dbfile)
new_agent = FeedForwardActor(policy_network=new_policy_network )
```
or using `savers.Snapshotter`, that also worked.
