### ISSUE TITLE
what is the helpers library

### ISSUE THREAD

**Issue by Mo379** [deepmind/acme#250]
In your continuous baseline example using PPO [here](https://github.com/deepmind/acme/blob/master/examples/baselines/rl_continuous/run_ppo.py), a library called 'helpers' is imported. I've just tried to run that code on my machine after cloning and installing ACME but without luck, the first trace states that the library is missing. I then execute 

pip install helpers

and re-run, but then helper.maker_environment(suite,task), line: 48 in the aforementioned link, spits out 'function doesn't exist'.

What is helpers ? and how do I install it ? 

Thanks

**Comment by kinalmehta** [comment]
It is not a library, it's just a file in the same directory with the example script. You need to `cd examples/baselines/rl_continuous/` and then run the ppo file. It should work fine then.

**Comment by Mo379** [comment]
simple enough, thanks
