### ISSUE TITLE
Regarding the papers "What Matters for Adversarial Imitation Learning?"

### ISSUE THREAD

**Issue by nuomizai** [deepmind/acme#253]
Hi, I'm interested in the paper "What Matters for Adversarial Imitation Learning?". However, I got confused when I read the Figure 76 (C7) and Figure 15 (C10). Take the environment Door human for example, the "95th percentile of performance scores conditioned on choice (top)" metric is almost zero in C10, but has a high value for C7. If I didn't take it wrong, both figures are hyperparameter-changing of PPO, while the only difference is one is `epoch` and one is `batch size`?
[C7](https://github.com/nuomizai/images/blob/main/C7.png)
[C10](https://github.com/nuomizai/images/blob/main/C10.png)

**Comment by sinopalnikov** [comment]
Hello, you should better contact the corresponding author for the paper: marcina@google.com

**Comment by nuomizai** [comment]
> Hello, you should better contact the corresponding author for the paper: [marcina@google.com](mailto:marcina@google.com)

Thanks for your reply, still.
