### ISSUE TITLE
pip install dm-acme[jax] has problem

### ISSUE THREAD

**Issue by ruyikang** [deepmind/acme#254]
I followed the instruction of the installation. However, some bad things happened. This is a amd computer, window system and use Python 3.9.13. 
pip install dm-acme[tensorflow] works well. But pip install dm-acme[jax] is not. It said that cannot connect github. I donnot know what happened. Meanwhile, why all instruction are mac and linux, no window here.

(acme) C:\Users\18100>pip install dm-acme[jax]
Requirement already satisfied: dm-acme[jax] in c:\users\18100\acme\lib\site-packages (0.2.4)
Requirement already satisfied: numpy in c:\users\18100\acme\lib\site-packages (from dm-acme[jax]) (1.23.1)
Requirement already satisfied: dm-env in c:\users\18100\acme\lib\site-packages (from dm-acme[jax]) (1.5)
Requirement already satisfied: typing-extensions in c:\users\18100\acme\lib\site-packages (from dm-acme[jax]) (4.3.0)
Requirement already satisfied: pillow in c:\users\18100\acme\lib\site-packages (from dm-acme[jax]) (9.2.0)
Requirement already satisfied: dm-tree in c:\users\18100\acme\lib\site-packages (from dm-acme[jax]) (0.1.7)
Requirement already satisfied: absl-py in c:\users\18100\acme\lib\site-packages (from dm-acme[jax]) (1.2.0)
Collecting keras==2.7.0
  Using cached keras-2.7.0-py2.py3-none-any.whl (1.3 MB)
Collecting rlax
  Using cached rlax-0.1.2-py3-none-any.whl (117 kB)
Requirement already satisfied: jax in c:\users\18100\acme\lib\site-packages (from dm-acme[jax]) (0.3.15)
Collecting flax
  Using cached flax-0.5.3-py3-none-any.whl (202 kB)
Collecting chex
  Using cached chex-0.1.3-py3-none-any.whl (72 kB)
Collecting optax
  Using cached optax-0.1.3-py3-none-any.whl (145 kB)
Collecting tensorflow-datasets==4.4.0
  Using cached tensorflow_datasets-4.4.0-py3-none-any.whl (4.0 MB)
Collecting dm-haiku
  Using cached dm_haiku-0.0.7-py3-none-any.whl (342 kB)
Collecting dm-acme[jax]
  Using cached dm-acme-0.4.0.tar.gz (314 kB)
  Preparing metadata (setup.py) ... done
  Using cached dm-acme-0.3.0.tar.gz (309 kB)
  Preparing metadata (setup.py) ... done
  Using cached dm-acme-0.2.3.tar.gz (297 kB)
  Preparing metadata (setup.py) ... done
  Using cached dm-acme-0.2.2.tar.gz (236 kB)
  Preparing metadata (setup.py) ... done
  Using cached dm_acme-0.2.1-py3-none-any.whl
Collecting rlax@ git+git://github.com/deepmind/rlax.git#egg=rlax
  Cloning git://github.com/deepmind/rlax.git to c:\users\18100\appdata\local\temp\pip-install-x47ukp1u\rlax_2a9fd6dba7964caeb01f487a1c654e64
  Running command git clone --filter=blob:none --quiet git://github.com/deepmind/rlax.git 'C:\Users\18100\AppData\Local\Temp\pip-install-x47ukp1u\rlax_2a9fd6dba7964caeb01f487a1c654e64'
  fatal: unable to connect to github.com:
  github.com[0: 20.205.243.166]: errno=Unknown error

  error: subprocess-exited-with-error

  × git clone --filter=blob:none --quiet git://github.com/deepmind/rlax.git 'C:\Users\18100\AppData\Local\Temp\pip-install-x47ukp1u\rlax_2a9fd6dba7964caeb01f487a1c654e64' did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet git://github.com/deepmind/rlax.git 'C:\Users\18100\AppData\Local\Temp\pip-install-x47ukp1u\rlax_2a9fd6dba7964caeb01f487a1c654e64' did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by ruyikang** [comment]
Maybe, I understand. Jax does not support windows.

**Comment by alan-cooney** [comment]
You were probably behind a firewall, that's preventing an install of `rlax` directly from GitHub. In the latest version it comes from PyPI instead so this should no longer be an issue.
