### ISSUE TITLE
run_experiment allow different seeded/wrapped environments for train and eval

### ISSUE THREAD

**Issue by Andrewzh112** [deepmind/acme#256]
current training loop seems to use only one environment object and usually eval env needs to seeded differently and wrapped differently (e.g. video wrapper on the eval env only). Is there a way to achieve this without editing the whole run_experiment function?

**Comment by sinopalnikov** [comment]
run_experiment is initially intended to cover only simple use cases. more features will be added to it going forward.
for now you'd have to fork it and patch. or you can use make_distributed_experiment where ExperimentConfig.evaluator_factories are supported

**Comment by Andrewzh112** [comment]
> run_experiment is initially intended to cover only simple use cases. more features will be added to it going forward. for now you'd have to fork it and patch. or you can use make_distributed_experiment where ExperimentConfig.evaluator_factories are supported

alright got it thanks!!
