### ISSUE TITLE
Wrong recurrent state accessed in R2D2 Learner

### ISSUE THREAD

**Issue by ostap-viniavskyi** [deepmind/acme#259]
In R2D2 Learner you sample learning trajectories from Reverb in such a format that at some index `t` you have observation `x_t`, action `a_t`, reward `r_t`, and recurrent state of LSTM network `state_t` that the network had after processing the observation `x_t`. Doesn't this mean that when you apply unroll in the learner [(link to code)](https://github.com/deepmind/acme/blob/6e0df2f5f9cf2375412977e4fb40c1edcea436cb/acme/agents/jax/r2d2/learning.py#L118)  you use LSTM state from one step in the future, effectively leaking information from the future state?

**Comment by bshahr** [comment]
Hi ostap-viniavskyi,

Apologies for the late reply. I believe this was fixed last month but please reopen the issue if you still see a problem with the current state of the agent.

Thanks for your interest and happy Acming!

Bobak
