### ISSUE TITLE
TRPO / PPO / SAC implementations

### ISSUE THREAD

**Issue by batu** [deepmind/acme#27]
First off, thank you for this great library!

Is the team planning on implementing TRPO/PPO/SAC as well? 

I find it immensely valuable to be able to compare different families of algorithms within the same framework to reduce errors and have my results be more robust.

**Comment by bshahr** [comment]
Hi batu,

We absolutely agree! We foresee that Acme's repository of agents will grow and we hope that many of those agents will be algorithms that were not developed at DeepMind, and hopefully many of _these_ will come from the community. While we have no plan to implement TRPO/PPO/SAC in the immediate future, I think it's just a matter of time before someone, either at DeepMind or in the OS community, fills that gap.

Thanks for the question!

**Comment by batu** [comment]
Thank you very much!

**Comment by aslanides** [comment]
We might want to leave this open & tag it as 'good first issue' for newcomers. WDYT @mwhoffman ?

**Comment by Sheepsody** [comment]
Hi everyone,
I submitted an issue related to this one : #12 .
Is there an algorithm that I could open as a PR to work on it ?
Thank you,

**Comment by wookayin** [comment]
@aslanides It seems that there is an example code for SAC agent in a recent commit 244d88b80fd87c55b5fafccb2b8a30cba0cf0dd7, but the code for SAC hasn't been released yet. Do you have a plan to open-source them in the near future? Thanks, and greatly looking forward to it!

**Comment by mwhoffman** [comment]
Hi @wookayin, some example code managed to sneak in there. While the agent code itself isn't quite ready yet, we should be releasing it soon and we'll keep you updated!

**Comment by ethanluoyc** [comment]
@mwhoffman we have been internally testing implementing more agents (e.g. PETS, SAC, DrQ, SAC-AE) with Acme in our group. I am more than happy to exchange ideas on implementing more agents and hopefully contributing some of them upstream. Let me know if you are interested!

**Comment by wookayin** [comment]
From https://github.com/deepmind/acme/issues/149#issuecomment-938571533 : Finally arrived in a66672c484a12ee71f99a36afe2f0553e2c1a97f!

**Comment by vamsianumula** [comment]
Hi, I'm new to this and I would love to contribute. Can someone help me out?

**Comment by nikolamomchev** [comment]
Thanks for the questions.

It's been a while since there was some action on this thread so I'll be closing it.

In the meantime, PPO, SAC and many more were added to Acme. Currently we do not have plans to add TRPO.
