### ISSUE TITLE
Do you have NGU implementation?

### ISSUE THREAD

**Issue by GoingMyWay** [deepmind/acme#276]
Hi,  it is a great repo for RL research. In my humber opinion, it would be great if NGU (Never Give Up) can be added. Do you plan to release the NGU implementation?

**Comment by sinopalnikov** [comment]
Hi! Sorry, at the moment we don't have plans to add the NGU implementation to Acme.

**Comment by GoingMyWay** [comment]
> Hi! Sorry, at the moment we don't have plans to add the NGU implementation to Acme.

I see. Thanks.
