### ISSUE TITLE
MCTS agent: environment in simulation out of sync

### ISSUE THREAD

**Issue by graidl** [deepmind/acme#29]
I appreciate the initiative with this framework a lot, in general I find the code very clean and much easier to read and adapt than the one of other frameworks!
Currently, I am focusing on the MCTS agent and strongly believe that there is a bug concerning the separate environment inside the simulator: It runs out of sync with the main environment as it is not reset properly.

More specifically, when a new episode is started in the environment loop after the first episode has been finished, the main environment is reset, but the environment in the simulator is not. In the action selection, the tree search starts by creating a root node, selecting an action and this action should  then be performed by step. At this moment, the simulator's environment still has an old uninitialized state. It seems that this is usually a LAST state and an auto-reset is therefore performed. However, this happens too late, as then the observation of the initial state is returned instead of the intended result of the first action.

**Comment by aslanides** [comment]
Thanks for reporting this! I'll take a look soon and see if I can reproduce it.

**Comment by aslanides** [comment]
Thanks for reporting this -- this was quite an egregious bug! I've fixed it in the above commit; let me know if you have any other issues.
