### ISSUE TITLE
dm-acme[reverb] installation fail

### ISSUE THREAD

**Issue by EstherXSD** [deepmind/acme#34]
ERROR: Could not find a version that satisfies the requirement dm-reverb-nightly==0.1.0.dev20200605; extra == "reverb" (from dm-acme[reverb]) (from versions: none)
ERROR: No matching distribution found for dm-reverb-nightly==0.1.0.dev20200605; extra == "reverb" (from dm-acme[reverb])
I’m now using python 3.7.5.

**Comment by fastturtle** [comment]
Hi @EstherXSD, what OS are you using? Reverb only supports Linux based OSes.

**Comment by EstherXSD** [comment]
Hi @fastturtle , Oh I initially installed it on Windows, now I have changed it to Ubuntu 20.04, python 3.7.7 
I can successfully install dm-acme[reverb] sperately as
`$ pip3 install tf-nightly==2.3.0.dev20200604
$ pip3 install dm-reverb-nightly`
but failed when performing 
`python3 -m venv acme
source acme/bin/activate
pip install dm-acme[reverb]`
The actual results said that
`Collecting tf-nightly==2.3.0.dev20200604
Killed`
I'm wondering whether I still need to download it with acme activated. And how can I solve this problem. Thank you!

**Comment by EstherXSD** [comment]
I think it may not due to my memeory limits, since as the figure shows, there is enough space...

**Comment by fastturtle** [comment]
Hi @EstherXSD, can you try to `pip install dm-acme` before you do `pip instal dm-acme[reverb]`? Are there any other logs you can show when you attempt to install?

**Comment by EstherXSD** [comment]
@fastturtle Hi, I solved it! Thanks you so much.

**Comment by fastturtle** [comment]
Glad to hear! It'd be good for future reference if you could explain your
solution.
