### ISSUE TITLE
add_first doc says timestep but code takes observation 

### ISSUE THREAD

**Issue by drozzy** [deepmind/acme#39]
Just a discrepancy between the doc and the code sample.

On this doc page: https://github.com/deepmind/acme/blob/master/docs/components.md

It says:
> The add_first() method takes the first timestep of an episode and adds it to the buffer

yet in the code example later it is shown:

```
adder.add_first(timestep.observation)
```

**Comment by bshahr** [comment]
Thanks for the catch! This is now fixed :)
