### ISSUE TITLE
Distributed training examples?

### ISSUE THREAD

**Issue by miriaford** [deepmind/acme#4]
It looks like all of the scripts in the examples are single-process. Are there any examples for distributed training? 
The paper mentions "Launchpad" that manages distributed processes - when do you plan to open-source that?

**Comment by bshahr** [comment]
Hi miriaford!
We have only open-sourced our single-process agents. While the code that is run in our distributed agents is identical to the open-sourced agents, the former are indeed tied to Launchpad and other DeepMind infrastructure. We don’t currently have a timetable for releasing these components. We’ll update the docs accordingly. Thanks for your question and interest in Acme!

**Comment by tomhennigan** [comment]
FYI Launchpad has been released (https://github.com/deepmind/launchpad, https://deepmind.com/research/open-source/launchpad) and distributed acme agents using launchpad were added in 3bc0426b.

**Comment by davidireland3** [comment]
@tomhennigan is there an example anywhere for using acme with distributed training now launchpad has been released? I'm currently using ray and it feels slower than it should (most of the overhead comes from passing the data from the server it's stored in, to the learner).
