### ISSUE TITLE
Overlapping sequences vs. period and sequence length

### ISSUE THREAD

**Issue by drozzy** [deepmind/acme#40]
I'm not sure about this one, maybe I'm wrong...

Under [reverb adders ](https://github.com/deepmind/acme/blob/4fa8ebfe34f4566db615f23a278306b14b5cc5f1/docs/components.md#reverbadders) section in the doc, for the SequenceAdder you say:

> sequences can be overlapping (if the period parameter = sequence_length n) or non-overlapping (if period < sequence_length)

Do you mean the opposite maybe?

> sequences can be non-overlapping (if the period parameter = sequence_length n) or overlapping (if period < sequence_length)

**Comment by bshahr** [comment]
Good catch again, thanks!
