### ISSUE TITLE
NLP

### ISSUE THREAD

**Issue by chrislouis0106** [deepmind/acme#41]
Hi:
I want to ask whether the project can solve the NLP work or not.
I will appreciate it if you tell me. Thank you.

**Comment by Bihaqo** [comment]
Hi!
Acme is built for RL problems. So it can certainly be used for RL problems which have an NLP bent, but there is nothing in Acme that is NLP specific, so you might be better of focusing on a framework that specifically attacks NLP

**Comment by Ashappyboy** [comment]
thank, your advice is helpful for me.&nbsp;



---Original---

**Comment by UPstartDeveloper** [comment]
RL for NLP problems sounds cool! I'm curious @Ashappyboy dis you have a specific kind of problem were you thinking of?

@Bihaqo do you think an RL model would be able to learn how to write stories, for example? That's one of the first NLP use cases that pops into my mind.

**Comment by Ashappyboy** [comment]
ENN,it is depend on your task. for me, i am special at the KG reason, RL is a good method to deal with the case. for other aspect, you can also try to use the RL methodlogy to slove it.



---Original---

**Comment by nikolamomchev** [comment]
Thanks for the question, I believe it was answered sufficiently well and I will be closing the issue.

If you still have questions, please submit them separately and we'll try to answer to the best of our abilities.
