### ISSUE TITLE
Agent evaluation and results 

### ISSUE THREAD

**Issue by rasoolfa** [deepmind/acme#43]
Hi,

Thanks for sharing this repo.
I have a suggestion: it would be super useful if you can provide examples of how to evaluate an agent and report results (like for DQN or DDPG). I see an example in tutorial, but it is more about displaying videos not reporting results.
This way, one can directly compare with Deepmind's papers and comparison would be very consistent and meaningful.
Thanks.

**Comment by pesapower** [comment]
It would be also useful having some methods to evaluate an agent during the training (i.e. every 10 episodes perform an agent evaluation). 
Bests.

**Comment by qstanczyk** [comment]
Please have a look at the new [examples](https://github.com/deepmind/acme/blob/master/examples/baselines/rl_continuous/run_ppo.py) which support on-line evaluation by default.
