### ISSUE TITLE
Using annealing epsilon greedy policy

### ISSUE THREAD

**Issue by honglu2875** [deepmind/acme#44]
I found out about this amazing library last week (such a great job and thank you for making it public!) and I have been working on adapting my own environments and agents to acme classes. I have one small question.

I noticed that in the DQN agent it uses a constant 0.05 epsilon greedy policy for action selection. https://github.com/deepmind/acme/blob/eb63054ec19525fa8320fb323327cf13495615e3/acme/agents/tf/dqn/agent.py#L119 
Now if I want to use a linearly annealing epsilon based on the number of total steps, what should be the proper way of coding it? 

In the code it adds a layer below the network to apply epsilon greedy. I guess it's not impossible for the network to take the number of total steps as an extra input, and feed it all the way down to a modified trfl.epsilon_greedy with annealing. But it seems I need to make many changes to different components and I really doubt whether this the proper way by design. Also I don't know whether this is already a function in the library. 

Again, I haven't been working on it for a lot of days. If it turns out to be a stupid question I apologize. Thank you!

**Comment by aslanides** [comment]
The simplest/easiest way to do this would probably be to just remove the epsilon greedy op from the network stack and implement this on the actor side, and implement the annealing schedule in plain python within the actor.

If you want to go for a more modular/'clean' approach, then you could define a simple Sonnet module that implements the epsilon greedy + annealing by keeping its own counter tf.Variable that tracks how many steps it has done.

Hope that makes sense!

**Comment by nikolamomchev** [comment]
Thanks for the question, I believe it was answered sufficiently well and I will be closing the issue.

If you still have questions, please submit them separately and we'll try to answer to the best of our abilities.
