### ISSUE TITLE
DQN crashes on tensorflow 2.3rc

### ISSUE THREAD

**Issue by honglu2875** [deepmind/acme#45]
First of all, I run everything on Google Colab. I don't know if this issue is worth reporting, because right now the stable version of tensorflow is 2.2 and dqn has no problems on it. But in certain circumstances I got errors saying tensorflow 2.2 is not high enough (For details please see the end of the post. Let me know if you want me to open up a separate issue and describe it in more details). But anyway, the crash happens if you install tensorflow 2.3.0rc0. The problem can be reproduced in the following very simple colab notebook (run the 1st cell, restart the runtime and run 2-4th cells):

https://colab.research.google.com/drive/1jcOWwdHPqqrA0Yp97SYyeuHiotDAdU0W?usp=sharing

Because there was no error message, I really had no idea about what's going on. I tried to use stupid debugging methods and I was able to figure out that the problem was possibly (not 100% sure though) caused by reverb.TFClient.update_priorities in the following line

https://github.com/deepmind/acme/blob/eb63054ec19525fa8320fb323327cf13495615e3/acme/agents/tf/dqn/learning.py#L153

For my own project, I finally realized that the solution is very simple: I load the packages in the right order and the tensorflow version error goes away. I stay in tensorflow 2.2 and nothing goes wrong. But I don't know if this is something worth noting in your project, and I post it here just in case. I would also like to know what caused it just for the sake of my curiosity.

------------
About the tensorflow version error:
In google colab, if I already imported tensorflow and then install acme packages, I would come across the following error when I tried to import acme.adders.reverb

> ImportError: This version of Reverb requires TensorFlow version >= 2.3.0; Detected an installation of version 2.2.0. Please upgrade TensorFlow to proceed.

I would also have problems loading acme.tf.networks but the error is a different one. All errors will be gone if I force to install tensorflow 2.3.0rc0. Let me know if you need more details.

**Comment by fastturtle** [comment]
Hi @honglu2875 thanks for reporting this issue. Reverb is fairly rigid with the versions of TF that can be used with it. When we compile Reverb we have to do so against a specific version of TF, and errors will be raised if it differs significantly from the system's version.

To that extent our error message:

> ImportError: This version of Reverb requires TensorFlow version >= 2.3.0; Detected an installation of version 2.2.0. Please upgrade TensorFlow to proceed.

should be tightened, and restrict users to use the same version of TF that was used to compile Reverb. 

The good news is that TF 2.3 will have a stable release soon, which means we will be have a stable Reverb release!

**Comment by qstanczyk** [comment]
Please re-open if this is still an issue for you.
