### ISSUE TITLE
[Error] Acme cannot build on ppc64le

### ISSUE THREAD

**Issue by AlessandroZavoli** [deepmind/acme#48]
It seems not possible to build acme on ppc64le. 
Did anybody tried to compile on an architecture different from "x86_64"?

Alessandro

**Comment by fastturtle** [comment]
Hi @AlessandroZavoli, [Reverb](https://github.com/deepmind/reverb) (which Acme requires) only works on x86_64 architectures (in particular only on Linux OSes).

Please comment on Reverb if you're interested in using it on different architectures.
