### ISSUE TITLE
Saving and restoring model/network

### ISSUE THREAD

**Issue by vishnukmd7** [deepmind/acme#49]
Hi,

 I'm extremely new to both TF and Sonnet.

I was trying to figure out how to save and load a trained network. I was following what was written in https://github.com/deepmind/sonnet#tensorflow-saved-model , but cant figure out how to regenerate a my_module object, with the weights from the loaded model.

Thanks!

**Comment by skibarch** [comment]
Hello! All default agents use `tf2_savers.Checkpointer` to automatically save both network and optimizer state (every 60 minutes with default settings). It also automatically restores the latest checkpoint during agent creation.
