### ISSUE TITLE
documentation for IMPALA

### ISSUE THREAD

**Issue by yuvaramsingh94** [deepmind/acme#50]
Hi all,
   i am currently trying to implement/run IMPALA agent using acme. it will be helpful if documentation for IMPALA is added here.

**Comment by ReinholdM** [comment]
Hi! Hope you release the document about IMPALA on this framework.

**Comment by ethanluoyc** [comment]
I found the best documentation is the code itself, assuming that you are familiar with the IMPALA paper, the code should be relatively straightforward to navigate (I have done this myself)

I am happy to share some tips and insights if you have specific questions about the implementation.
