### ISSUE TITLE
dm_control environments and difference with dm_env

### ISSUE THREAD

**Issue by rasoolfa** [deepmind/acme#52]
Hi,

1. Where can I find list of all available environments( i.e. task names and domain names)? Say in the following examples, what are possible domain names and task names:
`from dm_control import suite`
`environment = suite.load(domain_name, task_name)
`
2. What is the difference between **dm_env** and **dm_control**?

Thanks.

**Comment by fastturtle** [comment]
Hi @rasoolfa:

1. You can find a list of all available domains [here](https://github.com/deepmind/dm_control/blob/master/dm_control/suite/README.md), most of them are listed in the [tech report](https://arxiv.org/abs/1801.00690) (updates are posted to the README).
2. [dm_env](https://github.com/deepmind/dm_env) is an environment API, which is used by [dm_control](https://github.com/deepmind/dm_control) (a library for Mujoco based physics tasks).

I'm closing this issue but please re-open if you have further questions.

**Comment by rasoolfa** [comment]
Thanks a lot for your answer.
