### ISSUE TITLE
Training become extremely slow after 20k steps

### ISSUE THREAD

**Issue by ARISES-Phase2** [deepmind/acme#54]
Hello,

I met a problem when using the D4PG agent and my customized environment. The training process becomes very slow after around 20k steps. I run multiple experiments and attached the agent wall time. I think the customized  environment is fine since there is no problem when I tested it on ray and RLlib. 
![agent_Walltime](https://user-images.githubusercontent.com/59093257/88797410-335b9f00-d19b-11ea-9222-2a2b4e4fd2c8.png)

Then I used time profile to evaluate the running loop. It turned out that self._actor.select_action(timestep.observation) and self._actor.update() are 10 times slower after 20k steps.

Do you have any ideas?

**Comment by ARISES-Phase2** [comment]
The attached figure is agent walltime.

**Comment by skibarch** [comment]
Hello! `Actor.update` method calls `self._learner.step()` only after `min_observations` got collected. It means that your agent doesn't learn before accumulating enough data. Updating the model takes some time, so your training loop might get much slower. Check whenever `learner.step()` is called during those 20k steps.

**Comment by ARISES-Phase2** [comment]
Hi @fastturtle, thanks for adding the question tag. I would like show some updates. I've conducted the experiments for multiple times, and this problem persists. Then I run the demo of MountainCarContinuous-v0. The same problem was observed as the agent walltime plot below:

![agent_Walltime_car](https://user-images.githubusercontent.com/59093257/89742045-54bb6580-da8e-11ea-9c1c-d078fbf15bda.png)


The code I used is very simple, which is the same as the quickstart.ipynb in the example folder:
import IPython
from acme import environment_loop
from acme import specs
from acme import wrappers
from acme.agents.tf import d4pg
from acme.tf import networks
from acme.tf import utils as tf2_utils
from acme.utils import loggers
import numpy as np
import sonnet as snt

env_car = gym.make('MountainCarContinuous-v0')
environment = wrappers.GymWrapper(env_car)
environment = wrappers.SinglePrecisionWrapper(environment)
environment_spec = specs.make_environment_spec(environment)
num_dimensions = np.prod(environment_spec.actions.shape, dtype=int)

observation_network = tf2_utils.batch_concat

policy_network = snt.Sequential([
    networks.LayerNormMLP((256, 256, 256), activate_final=True),
    networks.NearZeroInitializedLinear(num_dimensions),
    networks.TanhToSpec(environment_spec.actions),
])

critic_network = snt.Sequential([
    networks.CriticMultiplexer(),
    networks.LayerNormMLP((512, 512, 256), activate_final=True),
    networks.DiscreteValuedHead(vmin=-150., vmax=150., num_atoms=51),
])

from acme.utils.loggers.tf_summary import TFSummaryLogger
agent_logger = TFSummaryLogger(label='agent',logdir='TFlogger/d4pg_test_car/agent_logger')
env_loop_logger = TFSummaryLogger(label='env_loop',logdir='TFlogger/d4pg_test_car/env_loop_logger')

agent = d4pg.D4PG(
    environment_spec=environment_spec,
    policy_network=policy_network,
    critic_network=critic_network,
    observation_network=observation_network,
    sigma=1.0,
    logger=agent_logger,
    checkpoint=False
)


env_loop = environment_loop.EnvironmentLoop(
    environment, agent, logger=env_loop_logger)

env_loop.run(num_episodes=10000)`


I'm using the containers of Jupyter Docker, and I can provide the docker image if it could help you to reproduce the problem. I removed decoration @tf.function and tried to debug. It seems that the operations of tensorflow, such as tf.function(), are extremely slow at some point.

Hi @skibarch, thanks for your reply. I set min_observations to 1000. The agent start calling learner.step() at the very beginning, so I don't think this is the reason that caused the problem.

**Comment by fastturtle** [comment]
Thanks for providing the code you're using to run your experiments. Could you also check memory usage to see if this is related to #55?

Also, I doubt this is the issue, but setting min_observations to 1000 means that learning will happen after 1000 transitions have been added to replay. Lowering this even further (i.e. to 1) will cause training to begin as soon as possible.

**Comment by ARISES-Phase2** [comment]
Hi @fastturtle , thanks for your advice! Yes, the reason is the memory usage! The memory usage increases extremely fast as the transitions are added into memory replay. The default setting of docker is to assign 2GB memory for each container, and therefore the issue occurs very early (20-30k steps). At this point, the memory usage is approaching the limit, and the percentage of CPU drops to around 0. Somehow, it didn't trigger out of memory exception.  The docker stats are shown below :
![2gb_end](https://user-images.githubusercontent.com/59093257/89959140-9b969000-dc33-11ea-9523-c41968b68c82.PNG)

After assigning 8GB memory, the experiment can last longer, but memory usage still grows fast. The docker stats are shown below :
![8gb_mid](https://user-images.githubusercontent.com/59093257/89959279-efa17480-dc33-11ea-8ae5-6f7ca66f06a1.PNG)

The plot of agent wall time (2GB (green) vs 8 GB (orange):
![agent_Walltime_2gbvs8gb](https://user-images.githubusercontent.com/59093257/89959445-5757bf80-dc34-11ea-8413-b4f19f0648ca.png)
