### ISSUE TITLE
Non-Mandatory CSVLogger UID (or custom UID)?

### ISSUE THREAD

**Issue by RylanSchaeffer** [deepmind/acme#59]
`class CSVLogger` necessarily adds a mandatory uid:

`directory = paths.process_path(directory, 'logs', label, add_uid=True)`

Would adding an argument to the `CSVLogger` init function so as to disable uids be possible? It'd look like:

```
class CSVLogger(base.Logger):
  """Standard CSV logger."""

  _open = open

  def __init__(self,
               directory: str = '~/acme',
               label: str = '',
               time_delta: float = 0.,
               add_uid=True,
):

    directory = paths.process_path(directory, 'logs', label, add_uid=add_uid)
```

**Comment by RylanSchaeffer** [comment]
If you're open to PRs and support the argument, I could submit the PR.

**Comment by fastturtle** [comment]
Hi @RylanSchaeffer thanks for pointing this out, feel free to submit a PR to add this argument.
