### ISSUE TITLE
Use tensorflow probability JAX substrate to standardize the implementations

### ISSUE THREAD

**Issue by joaogui1** [deepmind/acme#61]
Tensorflow probability now has a jax [substrate](https://www.tensorflow.org/probability/api_docs/python/tfp/substrates/jax/distributions/Beta#examples), so I believe we could use it to standardize the random number generation across jax and tensorflow implementations.

Do you think that would help the project? If so I can open a PR

**Comment by bshahr** [comment]
Hi Joaogui1!
Thanks for offering to contribute! I don't think this kind of standardization would be particularly helpful but feel free to send a PR if you want and we can have a look.
