### ISSUE TITLE
FeedForwardActor does not support tfd.Distribution output

### ISSUE THREAD

**Issue by Kmeco** [deepmind/acme#62]
The [FeedForwardActor.select_action() ](https://github.com/deepmind/acme/blob/7eeeb24087419575a3b38e95769f5f4f7cd38514/acme/agents/tf/actors.py#L64) method includes a step to "maybe sample" if the output of the policy is a tfd.Distribution:

```    
def maybe_sample(output): 
  if isinstance(output, tfd.Distribution):
    output = output.sample()
  return output
```

The policy_network passed to the actor is being compiled to a tf.function() which does not seem to support tfd.Distribution output at compilation. 

A dummy example: 
```
import tensorflow as tf
import tensorflow_probability as tfp
import sonnet as snt

# Create the policy network.
policy_network = snt.Sequential([
    snt.nets.MLP([5, 3]),
    tfp.distributions.Categorical
])

evaluation_actor = actors.FeedForwardActor(policy_network)

evaluation_actor.select_action(tf.constant([[1., 1.], [1., 1.]]))
```

Output: 
\>>> TypeError: To be compatible with tf.eager.defun, Python functions must return zero or more Tensors; in compilation of <function Function._defun_with_scope.<locals>.wrapped_fn at 0x7f97704d7b70>, found return value of type <class 'tensorflow_probability.python.distributions.categorical.Categorical'>, which is not a Tensor.

A workaround is to use the [networks.StochasticSamplingHead() ](https://github.com/deepmind/acme/blob/7eeeb24087419575a3b38e95769f5f4f7cd38514/acme/tf/networks/stochastic.py#L42) but then the `maybe_sample()` step of the `FeedForwardActor.select_action()` seems to be useless. Am I missing something?

**Comment by bshahr** [comment]
Hi Kmeco,

Thank you for your question (and answer!). Indeed the code was not working as intended and has now been fixed. However, your proposed solution of adding `networks.StochasticSamplingHead()` to your policy network is still preferred, since relying on the `Actor` class for conditional sampling is significantly less efficient (2x slower acting in some cases).

Cheers,

Bobak
