### ISSUE TITLE
Do ACME developers plan to support the PyTorch library?

### ISSUE THREAD

**Issue by erfanMhi** [deepmind/acme#64]

**Comment by bshahr** [comment]
Hi erfanMhi,

Thanks for your question and interest. We have no plans to develop any PyTorch agents, however, we have aspired to build Acme to be agnostic to the tensor programming language. It should therefore in principle be possible to build a PyTorch agent with no, or minimal, changes to the library. If you are successful in doing so, we would love to have review your solution, incorporate any improvements, and point to your agent as an example PyTorch agent working in Acme.

Good luck and thanks in advance!

Bobak
