### ISSUE TITLE
Distributed Workers - Question

### ISSUE THREAD

**Issue by jeffreywillert** [deepmind/acme#68]
First of all, thanks for the great contribution to the RL world.  I look forward to spending more time with the Acme framework.  

After reading the paper (https://arxiv.org/pdf/2006.00979.pdf) and reading other issues (e.g. https://github.com/deepmind/acme/issues/4) it appears that there is not currently an option, aside from manually building it, to construct multiple workers for simulating episodes - is that correct?

I've relied primarily on Ray's RLlib up until now and would love to spend more time with Acme, but distributed "rollouts" are a necessity for my applications.

**Comment by dongfangyixi** [comment]
try to use https://parl.readthedocs.io/en/latest/parallel_training/setup.html

**Comment by fastturtle** [comment]
Hi @jeffreywillert this is something we are working on and we are currently considering how to best support this in OS.

**Comment by denfromufa** [comment]
@fastturtle any updates on this?

**Comment by fastturtle** [comment]
Good news is that we have decided how to go about doing this. It's hard to say exactly _when_ this will be released, but we're actively working on it and are hoping for Q1 or Q2 this year.

**Comment by qstanczyk** [comment]
Good news - Launchpad now provides [distributed training with GCP](https://github.com/deepmind/launchpad/blob/07f9a5deb7c81a7aa0a1dcd9f91d659f59d91452/launchpad/context.py#L54), so it is possible to run Acme agents on cloud at scale.
