### ISSUE TITLE
R2D3 Agent sets up Priority Table with Uniform Sampling

### ISSUE THREAD

**Issue by weichseltree** [deepmind/acme#69]
https://github.com/deepmind/acme/blob/7affeb0e03b5bad1cebc30d208e40c9819c1be5c/acme/agents/tf/r2d3/agent.py#L76

From the name of the table, the R2D3 paper, as well as the reverb documentation, I suspect that the referenced line of code should be

`sampler=reverb.selectors.Prioritized(0.8),`

and that the hyper-parameter should be added to the constructor.

**Comment by nikolamomchev** [comment]
@weichseltree this was submitted a while ago and we are no longer supporting this algorithm. You should feel free to fork and update it.

In any case, thank you very much for the suggestion!
