### ISSUE TITLE
CSV Logger does not close files.

### ISSUE THREAD

**Issue by aacorn** [deepmind/acme#70]
CSV Logger does not close files on exit. Causes write buffer to not be flushed and lost. This can be fixed by adding a close method to all logger types to pass the close signal down the wrapper chain and closing the file at the root (or passing for the terminal logger), then calling this method at the end of the environment loop. Likely caused by commit 6a429648ed8335445cd20426c30de168adbdcc38 on August 14.

Edit: Learner logger has a similar issue, requiring a call down the agent chain. A call to self._file.flush() may be more appropriate.

**Comment by fastturtle** [comment]
Hi @aacorn, the file should flush when it is eventually gc'd as you can see in [csv_test.py](https://github.com/deepmind/acme/blob/master/acme/utils/loggers/csv_test.py). Are you finding this not to be the case? Do you have a reproducible example?

**Comment by vaxenburg** [comment]
I'm having the same issue. `CSVLogger` won't flush when its instance is passed to `EnvironmentLoop`. Explicitly deleting it and garbage collecting doesn't seem to help either.

**Comment by sprakashdash** [comment]
The same in my case!

**Comment by sprakashdash** [comment]
Well I found a workaround to save them:
```
learner_logger = loggers.CSVLogger(label='Hopper_Learner',
                                        time_delta=learner_log_every)
loop_logger = loggers.CSVLogger(label='Hopper_Environment_Loop',
                                     time_delta=loop_log_every)
```
I have initiated these two loggers and when my experiment is complete, I can check the directory by doing:
```
print(loop_logger.file_path)
print(learner_logger.file_path)
```
But they were empty. So doing this:
```
loop_logger._file.close()
learner_logger._file.close()
```
 solves my problem and the CSV files are now populated with the results!!!

**Comment by sprakashdash** [comment]
I have created a pull request.. #147
