### ISSUE TITLE
Problem with SequenceAdder and reverb adders test_utils 

### ISSUE THREAD

**Issue by RaoulDrake** [deepmind/acme#74]
Hi there, 

first of all thank you very much for sharing such a flexible and modular library for RL, it's really an excellent base for new projects and thus highly appreciated!

I've noticed a problem/possible bug with regard to the padding in SequenceAdder, which extends to the reverb adder package's test_utils.py: It seems to me that the padding in SequenceAdder actually does not happen. The problem is in [this line](https://github.com/deepmind/acme/blob/master/acme/adders/reverb/sequence.py#L100):

    padding = self._period - (self._step - self._max_sequence_length)

As soon as self._step >= self._max_sequence_length + self._period (which will eventually happen in most use-cases), padding becomes negative (or 0, in case of >=). As a result, the for loop in [these lines](https://github.com/deepmind/acme/blob/master/acme/adders/reverb/sequence.py#L102-L106) 

    for _ in range(padding):
      self._buffer.append(zero_step)
      self._writer.append(zero_step)
      self._step += 1

is never entered, since range(x) returns an empty sequence for x <= 0. 

Effectively, this results in SequenceAdder discarding any experience that should normally be padded, since self._step was never incremented in the for loop mentioned above and thus, calling self._maybe_add_priorities() in [this line](https://github.com/deepmind/acme/blob/master/acme/adders/reverb/sequence.py#L109) never actually results in creating an item in the reverb table.

The problem can be fixed by changing [this line](https://github.com/deepmind/acme/blob/master/acme/adders/reverb/sequence.py#L100):

    padding = self._period - (self._step - self._max_sequence_length)

to 

    padding = 0
    if (self._step - self._max_sequence_length) % self._period != 0:
      padding = self._period - ((self._step - self._max_sequence_length) % self._period)

The reason the problem doesnt' pop up in the tests for SequenceAdder lies in adders/reverb/test_utils.py, in [these lines](https://github.com/deepmind/acme/blob/master/acme/adders/reverb/test_utils.py#L195-L203):

    observed_items = [p[1] for p in self.client.writers[0].priorities]
    for expected_item, observed_item in zip(expected_items, observed_items):
      tree.map_structure(
          np.testing.assert_array_almost_equal,
          expected_item,
          observed_item,
          check_types=False)

When zip() encounters sequences of different length, it will zip according to the length of the sequence with the smaller length. 
Therefore, whenever there are less observed_items than expected_items, test cases will pass even though they should fail.
This can be fixed by checking that there are as many observed items as expected items: 

    self.assertEqual(len(observed_items), len(expected_items))
    for expected_item, observed_item in zip(expected_items, observed_items):
      ...

As a result of applying this fix to test_utils, the EarlyTerminationNoPadding test case in sequence_test will fail. In this testacse, pad_end_of_episode = False, and the testcase expects a non-padded, unfinished sequence. However, applying the padding fix  in SequenceAdder as mentioned above will still have the result of discarding unfinished sequences when pad_end_of_episode = False. So if the expected behaviour of SequenceAdder should be to write unfinished sequences when pad_end_of_episode = False, my fix mentioned above will not achieve this (although it could be implemented easily, e.g. by passing an argument to self._maybe_add_priorities() that indicates whether an unfinished sequence should be written to the buffer). On the other hand, if the fix suggested above is the behaviour you intended, this test case should expect an empty sequence.

I have implemented these suggested changes in my [fork](https://github.com/RaoulDrake/acme) of acme. With regard to the EarlyTerminationNoPadding test case, I have assumed that an empty sequence should be the expected behaviour and have modified the test case accordingly. I have also tested all other tests in reverb/adders after adding the suggested change to test_utils.py and they all pass (after making the suggested changes to sequence_test.py).
If you want, I'm happy to issue a pull request.

Best regards.

**Comment by fastturtle** [comment]
Hi @RaoulDrake thanks for filing this issue and for the detailed writeup! Was this fixed by 67d320ff678bddcab2571dbd126a59b8b4ae8606?

**Comment by nikolamomchev** [comment]
I'm closing the issue as it seems stale. Please re-submit if you have further questions.
