### ISSUE TITLE
Float 64 precision

### ISSUE THREAD

**Issue by yiwc** [deepmind/acme#76]
Hi, is there a method to choose float32 or float64 training precision? or mixed?

Thanks

**Comment by nikolamomchev** [comment]
This comment question is quite old and it may not be relevant for you any more. Also, it's unclear if you are asking about TF or JAX.

In any case, let me answer it as much as I can for future reference:
Acme will not set this internally and you are free to set it yourself. For jax you can do this in your main script. See this page for details: https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#double-64bit-precision

I assume the answer for TF would be similar.
