### ISSUE TITLE
Concatenation of observations with actions fails

### ISSUE THREAD

**Issue by notreadyyet** [deepmind/acme#78]
Please pardon newbie's question:why the following line 
outputs = tf2_utils.batch_concat([observation, action])
in file /acme/tf/networks/multiplexers.py fails?
The error is: "str: cannot compute ConcatV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:ConcatV2] name: concat"
Can't actions be discrete and observations float as on the attached picture? 
![acme_001](https://user-images.githubusercontent.com/37218428/95902161-66f1a280-0d62-11eb-8bf2-ecb47fdd2a15.png)
I tried to follow this example
https://github.com/deepmind/acme/blob/master/examples/control_suite/run_d4pg.py
while using my own environment class. This test runs on Ubuntu 18.04 in Anaconda environment with tensorflow 2.2.0 as shown at the bottom of the picture.
Thanks.

**Comment by bshahr** [comment]
Hi notreadyyet,

Thanks for your question. I think in your case it's a simple matter of casting your actions to floats before the concatenation. I believe the simplest way to do this would be to pass something like `action_network=functools.partial(tf.cast, dtype=tf.float32)` to the CriticMultiplexer component of the critic (L78 of the run_d4pg script).

Hope this helps, let me know one way or another!

Bobak

**Comment by notreadyyet** [comment]
Thank you, Bobak,  for a competent suggestion.
Please pardon my ignorance: wouldn't, after such casting, an instance of d4pg.D4PG class send float actions to my custom environment? Its "step" function wouldn't know what to do with actions such as 0.35...
Thanks again.

> Hi notreadyyet,
> 
> Thanks for your question. I think in your case it's a simple matter of casting your actions to floats before the concatenation. I believe the simplest way to do this would be to pass something like `action_network=functools.partial(tf.cast, dtype=tf.float32)` to the CriticMultiplexer component of the critic (L78 of the run_d4pg script).
> 
> Hope this helps, let me know one way or another!
> 
> Bobak

**Comment by nikolamomchev** [comment]
Closing this issue as it is likely no longer relevant. Please re-submit it if it is and we'll take a look.
