### ISSUE TITLE
R2D2 support for continuous (Bounded) environments 

### ISSUE THREAD

**Issue by chrispoulin** [deepmind/acme#79]
> # As per r2d2/agent_test.py, loading the fake environment with a Discrete array runs fine
# # print(spec.actions)
# # DiscreteArray(shape=(), dtype=int32, name=None, minimum=0, maximum=0, num_values=1)
> 
> # However, a Bounded Array float (e.g. from dm_control) causes an attribution error (need to add a flatten func?) 
#  # print(spec.actions)
# # BoundedArray(shape=(1,), dtype=dtype('float32'), name=None, minimum=[-1.], maximum=[1.])
> # Note: In contrast, D4PG does support this float32 behavior. R2d2 error message below:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-d8e2ab2bafe0> in <module>
     71 agent = r2d2.R2D2(
     72         environment_spec=spec,
---> 73         network=SimpleNetwork(spec.actions),
     74         batch_size=10,
     75         samples_per_insert=2,

~/acme/lib/python3.7/site-packages/sonnet/src/base.py in __call__(cls, *args, **kwargs)
    124     # Now attempt to initialize the object.
    125     try:
--> 126       module.__init__(*args, **kwargs)
    127     except:
    128       # We must explicitly catch so that in Python 2 sys.exc_info() is populated

<ipython-input-1-d8e2ab2bafe0> in __init__(self, action_spec)
     52         snt.Flatten(),
     53         snt.LSTM(20),
---> 54         snt.nets.MLP([50, 50, action_spec.num_values])
     55     ])
     56 

AttributeError: 'BoundedArray' object has no attribute 'num_values'

**Comment by fastturtle** [comment]
Hi @chrispoulin, thanks for raising this. R2D2 uses q-learning, which only applies to discrete action spaces. If you'd like to use an environment that has continuous actions you'll have to either: 1) discretize its action space or 2) use a different algorithm (e.g. D4PG, MPO, etc...).

**Comment by chrispoulin** [comment]
Hi @fastturtle, thank you for the update. I was unaware of this subtlety in terms of the q-learner's implementation. Will do as you suggest.
