### ISSUE TITLE
PyPI tf-nightly version incompatible

### ISSUE THREAD

**Issue by colingwuyu** [deepmind/acme#81]
setup.py extra installation requirements for tf-nightly==2.4.0.dev20200708 is no longer available in PyPI.
pip install dm-acme[tf] and dm-acme[reverb] fails in finding the required version.

**Comment by fastturtle** [comment]
Hi @colingwuyu, thanks for raising this issue. We're releasing Acme v0.2.0 which will fix this. We will update this bug when it is available on pypi.

**Comment by colingwuyu** [comment]
@fastturtle thank you for the swift response.

**Comment by fastturtle** [comment]
dm-acme 0.2.0 has been released on pypi, you should now be able to install the new version correctly :)
