### ISSUE TITLE
Contribute new logger?

### ISSUE THREAD

**Issue by kamil-kaczmarek** [deepmind/acme#84]
Hi,

First of all thanks for the great library and [accompanying paper](https://arxiv.org/abs/2006.00979)!

Together with my friend we wanted to contribute new logger to acme, neptune-logger. It will let acme and neptune users automatically log their runs to Neptune (it is [experiment tracking tool](https://docs.neptune.ai/index.html)).

Can I open draft PR, so that we can continue working on it from there?

Please let me know what do you think this idea?

**Comment by kamil-kaczmarek** [comment]
Hey,

Anybody here? :slightly_smiling_face:

**Comment by bshahr** [comment]
Hi Kamil,

I think this is a brilliant idea and encourage you to build it! However I don't think it makes sense to include it in the Acme repository as it is a very specific use-case and may introduce unnecessary dependencies; therefore such a logger sounds more appropriately housed in the Neptune code base.

Let us know if we can advise on way or another!

Bobak

**Comment by kamil-kaczmarek** [comment]
Hi @bshahr ,

Thanks for the info!

I observe that our users really like ACME, as some of them are actively using it in their research. To that end I want to make their experience with both tools better. 

Notably, such logger will not introduce additional dependencies in your library. We have similar integration with PyTorch-Lightning, where we simply capture exception on import - [see in the code](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/loggers/neptune.py#L22). We also explain in the documentation the installation procedure.

Nevertheless, if you do not feel that it's a good match, then housing ACME-Neptune logger in the Neptune codebase sound reasonable too. To that end, I think it would be great to mention it in the ACME docs in the [loggers section](https://github.com/deepmind/acme/blob/master/docs/components.md#loggers), to make it discoverable by researchers using ACME.

Please let me know if you see good fit here, thanks!

Regards,
Kamil

**Comment by kamil-kaczmarek** [comment]
hi @bshahr ,

Just a friendly reminder about the above (brief) discussion. Please let me know what do you think.

Regards,
Kamil

**Comment by nikolamomchev** [comment]
@kamil-kaczmarek sorry for the slow response on this. In case you've built the logger in the meantime and if you are still interested in adding a link to the Acme documentation, please send us a PR request to do that.
