### ISSUE TITLE
Intuition behind layer normalization

### ISSUE THREAD

**Issue by maciejwolczyk** [deepmind/acme#92]
I've noticed that you're using LayerNorm in most of your network architectures. Is there an intuitive explanation or theoretical justification why it is so helpful?

From my experience using layer normalization very often improves the empirical results. For example, when training SAC on Mujoco from pixels the layer normalization is pretty much required because everything falls apart without it (average return falls from ~250 to ~2 when you remove the LayerNorm). It is much appreciated that it helps, but I haven't really seen any discussion about the impact it has on training and I couldn't trace the first publication or codebase that used it. Do you have a working theory on the role of layer normalization in RL? Thanks!

**Comment by nikolamomchev** [comment]
I believe it is not specific to RL. I think this paper is the one which introduced layer normalization: https://arxiv.org/pdf/1607.06450.pdf
