### ISSUE TITLE
from acme.adders import reverb as adders not working

### ISSUE THREAD

**Issue by yashvirsinghgrewal-crypto** [deepmind/acme#93]
Hi, it seems like reverb is not getting imported properly. I am getting this issue when running the tutorial notebook on Colab:
![Screen Shot 2021-01-05 at 8 13 40 pm](https://user-images.githubusercontent.com/58552279/103628203-c55da400-4f92-11eb-8747-45e7b4303f6b.png)

**Comment by fastturtle** [comment]
Hi, this is likely due to a TensorFlow version mismatch. Acme requires TF version 2.4, which are you using?

**Comment by yashvirsinghgrewal-crypto** [comment]
Yes that's exactly what the reason was. Thanks for the reply.
